# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/krl1to5/Work/FULL/Sequence-ToolKit/2016/resources/ui/widgets/treewidget_tab.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tree_widget_tab(object):
    def setupUi(self, tree_widget_tab):
        tree_widget_tab.setObjectName("tree_widget_tab")
        tree_widget_tab.resize(662, 386)
        self.gridLayout = QtWidgets.QGridLayout(tree_widget_tab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tree_widget = QtWidgets.QTreeWidget(tree_widget_tab)
        self.tree_widget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tree_widget.setLineWidth(0)
        self.tree_widget.setTabKeyNavigation(True)
        self.tree_widget.setProperty("showDropIndicator", False)
        self.tree_widget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.tree_widget.setAlternatingRowColors(True)
        self.tree_widget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tree_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tree_widget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tree_widget.setIndentation(0)
        self.tree_widget.setUniformRowHeights(True)
        self.tree_widget.setItemsExpandable(False)
        self.tree_widget.setAnimated(True)
        self.tree_widget.setExpandsOnDoubleClick(False)
        self.tree_widget.setObjectName("tree_widget")
        self.tree_widget.header().setDefaultSectionSize(125)
        self.tree_widget.header().setHighlightSections(True)
        self.gridLayout.addWidget(self.tree_widget, 0, 0, 1, 1)
        self.action_copy = QtWidgets.QAction(tree_widget_tab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/img/icons/copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_copy.setIcon(icon)
        self.action_copy.setObjectName("action_copy")
        self.action_paste = QtWidgets.QAction(tree_widget_tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/img/icons/paste.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_paste.setIcon(icon1)
        self.action_paste.setObjectName("action_paste")
        self.action_cut = QtWidgets.QAction(tree_widget_tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/img/icons/cut.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_cut.setIcon(icon2)
        self.action_cut.setObjectName("action_cut")
        self.action_delete = QtWidgets.QAction(tree_widget_tab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/img/icons/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_delete.setIcon(icon3)
        self.action_delete.setObjectName("action_delete")
        self.action_merge = QtWidgets.QAction(tree_widget_tab)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resources/img/icons/merge.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_merge.setIcon(icon4)
        self.action_merge.setObjectName("action_merge")
        self.action_split = QtWidgets.QAction(tree_widget_tab)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resources/img/icons/split.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_split.setIcon(icon5)
        self.action_split.setObjectName("action_split")
        self.action_select_row = QtWidgets.QAction(tree_widget_tab)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/resources/img/icons/select_row.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_select_row.setIcon(icon6)
        self.action_select_row.setObjectName("action_select_row")
        self.action_group = QtWidgets.QAction(tree_widget_tab)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/resources/img/icons/group.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_group.setIcon(icon7)
        self.action_group.setObjectName("action_group")
        self.action_ungroup = QtWidgets.QAction(tree_widget_tab)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/resources/img/icons/ungroup.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ungroup.setIcon(icon8)
        self.action_ungroup.setObjectName("action_ungroup")

        self.retranslateUi(tree_widget_tab)
        QtCore.QMetaObject.connectSlotsByName(tree_widget_tab)

    def retranslateUi(self, tree_widget_tab):
        _translate = QtCore.QCoreApplication.translate
        tree_widget_tab.setWindowTitle(_translate("tree_widget_tab", "Form"))
        self.tree_widget.headerItem().setText(0, _translate("tree_widget_tab", "Group"))
        self.tree_widget.headerItem().setText(1, _translate("tree_widget_tab", "Sample"))
        self.action_copy.setText(_translate("tree_widget_tab", "&Copy"))
        self.action_copy.setStatusTip(_translate("tree_widget_tab", "Copy the current selection content to the clipboard."))
        self.action_paste.setText(_translate("tree_widget_tab", "&Paste"))
        self.action_paste.setStatusTip(_translate("tree_widget_tab", "Paste the clipboard content into the current selection."))
        self.action_cut.setText(_translate("tree_widget_tab", "C&ut"))
        self.action_cut.setStatusTip(_translate("tree_widget_tab", "Cut the current selection content to the clipboard."))
        self.action_delete.setText(_translate("tree_widget_tab", "&Delete"))
        self.action_delete.setStatusTip(_translate("tree_widget_tab", "Remove the current selection."))
        self.action_merge.setText(_translate("tree_widget_tab", "&Merge"))
        self.action_merge.setStatusTip(_translate("tree_widget_tab", "Merge several commands in the same process order."))
        self.action_split.setText(_translate("tree_widget_tab", "&Split"))
        self.action_split.setStatusTip(_translate("tree_widget_tab", "Split the selected merges."))
        self.action_select_row.setText(_translate("tree_widget_tab", "Select row"))
        self.action_group.setText(_translate("tree_widget_tab", "&Group"))
        self.action_group.setToolTip(_translate("tree_widget_tab", "Group"))
        self.action_ungroup.setText(_translate("tree_widget_tab", "&Ungroup"))
        self.action_ungroup.setToolTip(_translate("tree_widget_tab", "Ungroup"))

import img_rc
