# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/krl1to5/Work/FULL/Sequence-ToolKit/2016/resources/ui/stk/dialogs/properties.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_properties(object):
    def setupUi(self, properties):
        properties.setObjectName("properties")
        properties.resize(360, 409)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(properties)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tab_widget = QtWidgets.QTabWidget(properties)
        self.tab_widget.setObjectName("tab_widget")
        self.basic = QtWidgets.QWidget()
        self.basic.setObjectName("basic")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.basic)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layout_3 = QtWidgets.QHBoxLayout()
        self.layout_3.setSpacing(10)
        self.layout_3.setObjectName("layout_3")
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.setObjectName("layout")
        self.file_icon = QtWidgets.QLabel(self.basic)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_icon.sizePolicy().hasHeightForWidth())
        self.file_icon.setSizePolicy(sizePolicy)
        self.file_icon.setMinimumSize(QtCore.QSize(100, 120))
        self.file_icon.setMaximumSize(QtCore.QSize(100, 120))
        self.file_icon.setText("")
        self.file_icon.setScaledContents(True)
        self.file_icon.setObjectName("file_icon")
        self.layout.addWidget(self.file_icon)
        self.layout_3.addLayout(self.layout)
        self.layout_4 = QtWidgets.QVBoxLayout()
        self.layout_4.setSpacing(10)
        self.layout_4.setObjectName("layout_4")
        self.layout_5 = QtWidgets.QHBoxLayout()
        self.layout_5.setSpacing(8)
        self.layout_5.setObjectName("layout_5")
        self.file_name_label = QtWidgets.QLabel(self.basic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.file_name_label.setFont(font)
        self.file_name_label.setObjectName("file_name_label")
        self.layout_5.addWidget(self.file_name_label)
        self.file_name = QtWidgets.QLabel(self.basic)
        self.file_name.setText("")
        self.file_name.setObjectName("file_name")
        self.layout_5.addWidget(self.file_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_5.addItem(spacerItem)
        self.layout_4.addLayout(self.layout_5)
        self.layout_6 = QtWidgets.QHBoxLayout()
        self.layout_6.setSpacing(8)
        self.layout_6.setObjectName("layout_6")
        self.file_size_label = QtWidgets.QLabel(self.basic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.file_size_label.setFont(font)
        self.file_size_label.setObjectName("file_size_label")
        self.layout_6.addWidget(self.file_size_label)
        self.file_size = QtWidgets.QLabel(self.basic)
        self.file_size.setText("")
        self.file_size.setObjectName("file_size")
        self.layout_6.addWidget(self.file_size)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_6.addItem(spacerItem1)
        self.layout_4.addLayout(self.layout_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_4.addItem(spacerItem2)
        self.layout_3.addLayout(self.layout_4)
        self.verticalLayout_4.addLayout(self.layout_3)
        self.layout_7 = QtWidgets.QHBoxLayout()
        self.layout_7.setSpacing(8)
        self.layout_7.setObjectName("layout_7")
        self.accessed_label = QtWidgets.QLabel(self.basic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.accessed_label.setFont(font)
        self.accessed_label.setObjectName("accessed_label")
        self.layout_7.addWidget(self.accessed_label)
        self.accessed = QtWidgets.QLabel(self.basic)
        self.accessed.setText("")
        self.accessed.setObjectName("accessed")
        self.layout_7.addWidget(self.accessed)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_7.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.layout_7)
        self.layout_8 = QtWidgets.QHBoxLayout()
        self.layout_8.setSpacing(8)
        self.layout_8.setObjectName("layout_8")
        self.location_label = QtWidgets.QLabel(self.basic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.location_label.setFont(font)
        self.location_label.setObjectName("location_label")
        self.layout_8.addWidget(self.location_label)
        self.location = QtWidgets.QLabel(self.basic)
        self.location.setText("")
        self.location.setObjectName("location")
        self.layout_8.addWidget(self.location)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_8.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.layout_8)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.tab_widget.addTab(self.basic, "")
        self.sequence = QtWidgets.QWidget()
        self.sequence.setObjectName("sequence")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sequence)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_9 = QtWidgets.QHBoxLayout()
        self.layout_9.setSpacing(8)
        self.layout_9.setObjectName("layout_9")
        self.name_label = QtWidgets.QLabel(self.sequence)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.layout_9.addWidget(self.name_label)
        self.name = QtWidgets.QLabel(self.sequence)
        self.name.setText("")
        self.name.setObjectName("name")
        self.layout_9.addWidget(self.name)
        self.verticalLayout.addLayout(self.layout_9)
        self.layout_10 = QtWidgets.QHBoxLayout()
        self.layout_10.setSpacing(8)
        self.layout_10.setObjectName("layout_10")
        self.owner_label = QtWidgets.QLabel(self.sequence)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.owner_label.setFont(font)
        self.owner_label.setObjectName("owner_label")
        self.layout_10.addWidget(self.owner_label)
        self.owner = QtWidgets.QLabel(self.sequence)
        self.owner.setText("")
        self.owner.setObjectName("owner")
        self.layout_10.addWidget(self.owner)
        self.verticalLayout.addLayout(self.layout_10)
        self.layout_11 = QtWidgets.QHBoxLayout()
        self.layout_11.setSpacing(8)
        self.layout_11.setObjectName("layout_11")
        self.status_label = QtWidgets.QLabel(self.sequence)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.layout_11.addWidget(self.status_label)
        self.status = QtWidgets.QLabel(self.sequence)
        self.status.setText("")
        self.status.setObjectName("status")
        self.layout_11.addWidget(self.status)
        self.verticalLayout.addLayout(self.layout_11)
        self.layout_12 = QtWidgets.QHBoxLayout()
        self.layout_12.setSpacing(8)
        self.layout_12.setObjectName("layout_12")
        self.reader_id_label = QtWidgets.QLabel(self.sequence)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.reader_id_label.setFont(font)
        self.reader_id_label.setObjectName("reader_id_label")
        self.layout_12.addWidget(self.reader_id_label)
        self.reader_id = QtWidgets.QLabel(self.sequence)
        self.reader_id.setText("")
        self.reader_id.setObjectName("reader_id")
        self.layout_12.addWidget(self.reader_id)
        self.verticalLayout.addLayout(self.layout_12)
        self.layout_13 = QtWidgets.QHBoxLayout()
        self.layout_13.setSpacing(8)
        self.layout_13.setObjectName("layout_13")
        self.amount_label = QtWidgets.QLabel(self.sequence)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.amount_label.setFont(font)
        self.amount_label.setObjectName("amount_label")
        self.layout_13.addWidget(self.amount_label)
        self.amount = QtWidgets.QLabel(self.sequence)
        self.amount.setText("")
        self.amount.setObjectName("amount")
        self.layout_13.addWidget(self.amount)
        self.verticalLayout.addLayout(self.layout_13)
        self.layout_19 = QtWidgets.QHBoxLayout()
        self.layout_19.setSpacing(8)
        self.layout_19.setObjectName("layout_19")
        self.protocol_label = QtWidgets.QLabel(self.sequence)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.protocol_label.setFont(font)
        self.protocol_label.setObjectName("protocol_label")
        self.layout_19.addWidget(self.protocol_label)
        self.protocol = QtWidgets.QLabel(self.sequence)
        self.protocol.setText("")
        self.protocol.setObjectName("protocol")
        self.layout_19.addWidget(self.protocol)
        self.verticalLayout.addLayout(self.layout_19)
        self.layout_14 = QtWidgets.QHBoxLayout()
        self.layout_14.setSpacing(8)
        self.layout_14.setObjectName("layout_14")
        self.creaton_date_label = QtWidgets.QLabel(self.sequence)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.creaton_date_label.setFont(font)
        self.creaton_date_label.setObjectName("creaton_date_label")
        self.layout_14.addWidget(self.creaton_date_label)
        self.creaton_date = QtWidgets.QLabel(self.sequence)
        self.creaton_date.setText("")
        self.creaton_date.setObjectName("creaton_date")
        self.layout_14.addWidget(self.creaton_date)
        self.verticalLayout.addLayout(self.layout_14)
        self.layout_15 = QtWidgets.QHBoxLayout()
        self.layout_15.setSpacing(8)
        self.layout_15.setObjectName("layout_15")
        self.last_modification_label = QtWidgets.QLabel(self.sequence)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.last_modification_label.setFont(font)
        self.last_modification_label.setObjectName("last_modification_label")
        self.layout_15.addWidget(self.last_modification_label)
        self.last_modification = QtWidgets.QLabel(self.sequence)
        self.last_modification.setText("")
        self.last_modification.setObjectName("last_modification")
        self.layout_15.addWidget(self.last_modification)
        self.verticalLayout.addLayout(self.layout_15)
        self.layout_16 = QtWidgets.QHBoxLayout()
        self.layout_16.setSpacing(8)
        self.layout_16.setObjectName("layout_16")
        self.nitrogen_use_label = QtWidgets.QLabel(self.sequence)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nitrogen_use_label.setFont(font)
        self.nitrogen_use_label.setObjectName("nitrogen_use_label")
        self.layout_16.addWidget(self.nitrogen_use_label)
        self.nitrogen_use = QtWidgets.QLabel(self.sequence)
        self.nitrogen_use.setText("")
        self.nitrogen_use.setObjectName("nitrogen_use")
        self.layout_16.addWidget(self.nitrogen_use)
        self.verticalLayout.addLayout(self.layout_16)
        self.layout_17 = QtWidgets.QHBoxLayout()
        self.layout_17.setSpacing(8)
        self.layout_17.setObjectName("layout_17")
        self.dose_rate_label = QtWidgets.QLabel(self.sequence)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dose_rate_label.setFont(font)
        self.dose_rate_label.setObjectName("dose_rate_label")
        self.layout_17.addWidget(self.dose_rate_label)
        self.dose_rate = QtWidgets.QLabel(self.sequence)
        self.dose_rate.setText("")
        self.dose_rate.setObjectName("dose_rate")
        self.layout_17.addWidget(self.dose_rate)
        self.verticalLayout.addLayout(self.layout_17)
        self.layout_18 = QtWidgets.QHBoxLayout()
        self.layout_18.setSpacing(8)
        self.layout_18.setObjectName("layout_18")
        self.external_dose_rate_label = QtWidgets.QLabel(self.sequence)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.external_dose_rate_label.setFont(font)
        self.external_dose_rate_label.setObjectName("external_dose_rate_label")
        self.layout_18.addWidget(self.external_dose_rate_label)
        self.external_dose_rate = QtWidgets.QLabel(self.sequence)
        self.external_dose_rate.setText("")
        self.external_dose_rate.setObjectName("external_dose_rate")
        self.layout_18.addWidget(self.external_dose_rate)
        self.verticalLayout.addLayout(self.layout_18)
        self.tab_widget.addTab(self.sequence, "")
        self.verticalLayout_3.addWidget(self.tab_widget)
        self.line = QtWidgets.QFrame(properties)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.buttons_area = QtWidgets.QHBoxLayout()
        self.buttons_area.setObjectName("buttons_area")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons_area.addItem(spacerItem6)
        self.push_button_close = QtWidgets.QPushButton(properties)
        self.push_button_close.setMinimumSize(QtCore.QSize(100, 32))
        self.push_button_close.setObjectName("push_button_close")
        self.buttons_area.addWidget(self.push_button_close)
        self.verticalLayout_3.addLayout(self.buttons_area)

        self.retranslateUi(properties)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(properties)
        properties.setTabOrder(self.tab_widget, self.push_button_close)

    def retranslateUi(self, properties):
        _translate = QtCore.QCoreApplication.translate
        properties.setWindowTitle(_translate("properties", "Properties"))
        self.file_name_label.setText(_translate("properties", "File Name:"))
        self.file_size_label.setText(_translate("properties", "Size:"))
        self.accessed_label.setText(_translate("properties", "Accessed:"))
        self.location_label.setText(_translate("properties", "Location:"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.basic), _translate("properties", "Basic"))
        self.name_label.setText(_translate("properties", "Name:"))
        self.owner_label.setText(_translate("properties", "Owner:"))
        self.status_label.setText(_translate("properties", "Status:"))
        self.reader_id_label.setText(_translate("properties", "Reader ID:"))
        self.amount_label.setText(_translate("properties", "Samples amount:"))
        self.protocol_label.setText(_translate("properties", "Protocol:"))
        self.creaton_date_label.setText(_translate("properties", "Creation date:"))
        self.last_modification_label.setText(_translate("properties", "Last modification:"))
        self.nitrogen_use_label.setText(_translate("properties", "Nitrogen use:"))
        self.dose_rate_label.setText(_translate("properties", "Dose rate:"))
        self.external_dose_rate_label.setText(_translate("properties", "External dose rate:"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.sequence), _translate("properties", "Sequence"))
        self.push_button_close.setText(_translate("properties", "Close"))

