# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/krl1to5/Work/FULL/Sequence-ToolKit/2016/resources/ui/stk/dialogs/settings.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(380, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(settings)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_widget = QtWidgets.QTabWidget(settings)
        self.tab_widget.setObjectName("tab_widget")
        self.global_ = QtWidgets.QWidget()
        self.global_.setObjectName("global_")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.global_)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.language_layout = QtWidgets.QHBoxLayout()
        self.language_layout.setSpacing(10)
        self.language_layout.setObjectName("language_layout")
        self.language_label = QtWidgets.QLabel(self.global_)
        self.language_label.setObjectName("language_label")
        self.language_layout.addWidget(self.language_label)
        self.language = QtWidgets.QComboBox(self.global_)
        self.language.setMinimumSize(QtCore.QSize(90, 28))
        self.language.setMaximumSize(QtCore.QSize(90, 16777215))
        self.language.setObjectName("language")
        self.language_layout.addWidget(self.language)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.language_layout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.language_layout)
        self.frame = QtWidgets.QFrame(self.global_)
        self.frame.setMinimumSize(QtCore.QSize(0, 80))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.theme_layout = QtWidgets.QVBoxLayout()
        self.theme_layout.setObjectName("theme_layout")
        self.theme_label = QtWidgets.QLabel(self.frame)
        self.theme_label.setObjectName("theme_label")
        self.theme_layout.addWidget(self.theme_label)
        self.theme = QtWidgets.QComboBox(self.frame)
        self.theme.setMinimumSize(QtCore.QSize(0, 28))
        self.theme.setObjectName("theme")
        self.theme_layout.addWidget(self.theme)
        self.horizontalLayout_2.addLayout(self.theme_layout)
        self.skin_layout = QtWidgets.QVBoxLayout()
        self.skin_layout.setObjectName("skin_layout")
        self.skin_label = QtWidgets.QLabel(self.frame)
        self.skin_label.setObjectName("skin_label")
        self.skin_layout.addWidget(self.skin_label)
        self.skin = QtWidgets.QComboBox(self.frame)
        self.skin.setMinimumSize(QtCore.QSize(0, 28))
        self.skin.setObjectName("skin")
        self.skin_layout.addWidget(self.skin)
        self.horizontalLayout_2.addLayout(self.skin_layout)
        self.verticalLayout_3.addWidget(self.frame)
        self.location_layout = QtWidgets.QHBoxLayout()
        self.location_layout.setSpacing(10)
        self.location_layout.setObjectName("location_layout")
        self.location_label = QtWidgets.QLabel(self.global_)
        self.location_label.setObjectName("location_label")
        self.location_layout.addWidget(self.location_label)
        self.location_editable = QtWidgets.QHBoxLayout()
        self.location_editable.setObjectName("location_editable")
        self.location = QtWidgets.QLineEdit(self.global_)
        self.location.setEnabled(True)
        self.location.setMinimumSize(QtCore.QSize(0, 28))
        self.location.setReadOnly(True)
        self.location.setObjectName("location")
        self.location_editable.addWidget(self.location)
        self.location_explorer = QtWidgets.QToolButton(self.global_)
        self.location_explorer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.location_explorer.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/img/icons/explore.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.location_explorer.setIcon(icon)
        self.location_explorer.setIconSize(QtCore.QSize(30, 30))
        self.location_explorer.setObjectName("location_explorer")
        self.location_editable.addWidget(self.location_explorer)
        self.location_layout.addLayout(self.location_editable)
        self.verticalLayout_3.addLayout(self.location_layout)
        self.opacity_layout = QtWidgets.QHBoxLayout()
        self.opacity_layout.setSpacing(10)
        self.opacity_layout.setObjectName("opacity_layout")
        self.opacity_label = QtWidgets.QLabel(self.global_)
        self.opacity_label.setObjectName("opacity_label")
        self.opacity_layout.addWidget(self.opacity_label)
        self.opacity = QtWidgets.QSlider(self.global_)
        self.opacity.setMinimumSize(QtCore.QSize(160, 0))
        self.opacity.setMinimum(50)
        self.opacity.setMaximum(100)
        self.opacity.setSingleStep(10)
        self.opacity.setProperty("value", 100)
        self.opacity.setOrientation(QtCore.Qt.Horizontal)
        self.opacity.setInvertedAppearance(False)
        self.opacity.setInvertedControls(False)
        self.opacity.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.opacity.setObjectName("opacity")
        self.opacity_layout.addWidget(self.opacity)
        self.opacity_spinbox = QtWidgets.QDoubleSpinBox(self.global_)
        self.opacity_spinbox.setMinimumSize(QtCore.QSize(60, 28))
        self.opacity_spinbox.setDecimals(1)
        self.opacity_spinbox.setMinimum(0.5)
        self.opacity_spinbox.setMaximum(1.0)
        self.opacity_spinbox.setSingleStep(0.1)
        self.opacity_spinbox.setObjectName("opacity_spinbox")
        self.opacity_layout.addWidget(self.opacity_spinbox)
        self.verticalLayout_3.addLayout(self.opacity_layout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.tab_widget.addTab(self.global_, "")
        self.font_tab = QtWidgets.QWidget()
        self.font_tab.setObjectName("font_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.font_tab)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.font_layout = QtWidgets.QHBoxLayout()
        self.font_layout.setSpacing(10)
        self.font_layout.setObjectName("font_layout")
        self.font_family_label = QtWidgets.QLabel(self.font_tab)
        self.font_family_label.setObjectName("font_family_label")
        self.font_layout.addWidget(self.font_family_label)
        self.font_family = QtWidgets.QFontComboBox(self.font_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.font_family.sizePolicy().hasHeightForWidth())
        self.font_family.setSizePolicy(sizePolicy)
        self.font_family.setMinimumSize(QtCore.QSize(200, 28))
        self.font_family.setObjectName("font_family")
        self.font_layout.addWidget(self.font_family)
        self.verticalLayout_4.addLayout(self.font_layout)
        self.horizontal_layout = QtWidgets.QHBoxLayout()
        self.horizontal_layout.setObjectName("horizontal_layout")
        self.size_layout = QtWidgets.QHBoxLayout()
        self.size_layout.setSpacing(10)
        self.size_layout.setObjectName("size_layout")
        self.font_size_label = QtWidgets.QLabel(self.font_tab)
        self.font_size_label.setObjectName("font_size_label")
        self.size_layout.addWidget(self.font_size_label)
        self.font_size = QtWidgets.QSpinBox(self.font_tab)
        self.font_size.setMinimumSize(QtCore.QSize(50, 28))
        self.font_size.setMinimum(9)
        self.font_size.setMaximum(30)
        self.font_size.setObjectName("font_size")
        self.size_layout.addWidget(self.font_size)
        self.horizontal_layout.addLayout(self.size_layout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout.addItem(spacerItem2)
        self.style_layout = QtWidgets.QHBoxLayout()
        self.style_layout.setSpacing(10)
        self.style_layout.setObjectName("style_layout")
        self.style_label = QtWidgets.QLabel(self.font_tab)
        self.style_label.setObjectName("style_label")
        self.style_layout.addWidget(self.style_label)
        self.font_style = QtWidgets.QComboBox(self.font_tab)
        self.font_style.setMinimumSize(QtCore.QSize(100, 28))
        self.font_style.setObjectName("font_style")
        self.font_style.addItem("")
        self.font_style.addItem("")
        self.font_style.addItem("")
        self.font_style.addItem("")
        self.font_style.addItem("")
        self.style_layout.addWidget(self.font_style)
        self.horizontal_layout.addLayout(self.style_layout)
        self.verticalLayout_4.addLayout(self.horizontal_layout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.font_tab)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.font_testing = QtWidgets.QLineEdit(self.font_tab)
        self.font_testing.setMinimumSize(QtCore.QSize(0, 28))
        self.font_testing.setObjectName("font_testing")
        self.verticalLayout_2.addWidget(self.font_testing)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.tab_widget.addTab(self.font_tab, "")
        self.verticalLayout.addWidget(self.tab_widget)
        self.line = QtWidgets.QFrame(settings)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.buttons_area = QtWidgets.QHBoxLayout()
        self.buttons_area.setSpacing(10)
        self.buttons_area.setObjectName("buttons_area")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons_area.addItem(spacerItem4)
        self.push_button_accept = QtWidgets.QPushButton(settings)
        self.push_button_accept.setMinimumSize(QtCore.QSize(100, 32))
        self.push_button_accept.setObjectName("push_button_accept")
        self.buttons_area.addWidget(self.push_button_accept)
        self.push_button_cancel = QtWidgets.QPushButton(settings)
        self.push_button_cancel.setMinimumSize(QtCore.QSize(100, 32))
        self.push_button_cancel.setObjectName("push_button_cancel")
        self.buttons_area.addWidget(self.push_button_cancel)
        self.verticalLayout.addLayout(self.buttons_area)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)

        self.retranslateUi(settings)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "Settings"))
        self.language_label.setText(_translate("settings", "Language"))
        self.theme_label.setText(_translate("settings", "Theme"))
        self.skin_label.setText(_translate("settings", "Skin"))
        self.location_label.setText(_translate("settings", "Default Location"))
        self.location_explorer.setToolTip(_translate("settings", "Explore"))
        self.opacity_label.setText(_translate("settings", "Window Opacity"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.global_), _translate("settings", "Global"))
        self.font_family_label.setText(_translate("settings", "Font Family"))
        self.font_size_label.setText(_translate("settings", "Size"))
        self.style_label.setText(_translate("settings", "Style"))
        self.font_style.setItemText(0, _translate("settings", "Normal"))
        self.font_style.setItemText(1, _translate("settings", "Light"))
        self.font_style.setItemText(2, _translate("settings", "Book"))
        self.font_style.setItemText(3, _translate("settings", "Bold"))
        self.font_style.setItemText(4, _translate("settings", "Oblique"))
        self.label.setText(_translate("settings", "Test your text here"))
        self.font_testing.setText(_translate("settings", "AaBbCc123"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.font_tab), _translate("settings", "Font"))
        self.push_button_accept.setText(_translate("settings", "Accept"))
        self.push_button_cancel.setText(_translate("settings", "Cancel"))

import img_rc
