# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/krl1to5/Work/FULL/Sequence-ToolKit/2016/resources/ui/gensec/dialogs/criterias.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_criteria(object):
    def setupUi(self, criteria):
        criteria.setObjectName("criteria")
        criteria.resize(461, 245)
        self.verticalLayout = QtWidgets.QVBoxLayout(criteria)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.form_area = QtWidgets.QFrame(criteria)
        self.form_area.setFrameShape(QtWidgets.QFrame.Box)
        self.form_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.form_area.setObjectName("form_area")
        self.gridLayout = QtWidgets.QGridLayout(self.form_area)
        self.gridLayout.setContentsMargins(8, 8, 8, 8)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.criterion_label = QtWidgets.QLabel(self.form_area)
        self.criterion_label.setObjectName("criterion_label")
        self.gridLayout.addWidget(self.criterion_label, 0, 0, 1, 1)
        self.condition_label = QtWidgets.QLabel(self.form_area)
        self.condition_label.setObjectName("condition_label")
        self.gridLayout.addWidget(self.condition_label, 0, 1, 1, 1)
        self.value_label = QtWidgets.QLabel(self.form_area)
        self.value_label.setObjectName("value_label")
        self.gridLayout.addWidget(self.value_label, 0, 2, 1, 1)
        self.sample_id_label = QtWidgets.QLabel(self.form_area)
        self.sample_id_label.setObjectName("sample_id_label")
        self.gridLayout.addWidget(self.sample_id_label, 1, 0, 1, 1)
        self.condition_1 = QtWidgets.QComboBox(self.form_area)
        self.condition_1.setEnabled(True)
        self.condition_1.setMinimumSize(QtCore.QSize(160, 28))
        self.condition_1.setObjectName("condition_1")
        self.condition_1.addItem("")
        self.condition_1.addItem("")
        self.condition_1.addItem("")
        self.gridLayout.addWidget(self.condition_1, 1, 1, 1, 1)
        self.value_1 = QtWidgets.QLineEdit(self.form_area)
        self.value_1.setEnabled(False)
        self.value_1.setMinimumSize(QtCore.QSize(160, 28))
        self.value_1.setObjectName("value_1")
        self.gridLayout.addWidget(self.value_1, 1, 2, 1, 1)
        self.process_idlabel = QtWidgets.QLabel(self.form_area)
        self.process_idlabel.setObjectName("process_idlabel")
        self.gridLayout.addWidget(self.process_idlabel, 2, 0, 1, 1)
        self.condition_2 = QtWidgets.QComboBox(self.form_area)
        self.condition_2.setEnabled(True)
        self.condition_2.setMinimumSize(QtCore.QSize(160, 28))
        self.condition_2.setObjectName("condition_2")
        self.condition_2.addItem("")
        self.condition_2.addItem("")
        self.condition_2.addItem("")
        self.gridLayout.addWidget(self.condition_2, 2, 1, 1, 1)
        self.value_2 = QtWidgets.QLineEdit(self.form_area)
        self.value_2.setEnabled(False)
        self.value_2.setMinimumSize(QtCore.QSize(160, 28))
        self.value_2.setObjectName("value_2")
        self.gridLayout.addWidget(self.value_2, 2, 2, 1, 1)
        self.data_type_label = QtWidgets.QLabel(self.form_area)
        self.data_type_label.setObjectName("data_type_label")
        self.gridLayout.addWidget(self.data_type_label, 3, 0, 1, 1)
        self.condition_3 = QtWidgets.QComboBox(self.form_area)
        self.condition_3.setEnabled(True)
        self.condition_3.setMinimumSize(QtCore.QSize(160, 28))
        self.condition_3.setObjectName("condition_3")
        self.condition_3.addItem("")
        self.condition_3.addItem("")
        self.condition_3.addItem("")
        self.gridLayout.addWidget(self.condition_3, 3, 1, 1, 1)
        self.value_3 = QtWidgets.QLineEdit(self.form_area)
        self.value_3.setEnabled(False)
        self.value_3.setMinimumSize(QtCore.QSize(160, 28))
        self.value_3.setObjectName("value_3")
        self.gridLayout.addWidget(self.value_3, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.form_area)
        self.line = QtWidgets.QFrame(criteria)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.buttons_area = QtWidgets.QHBoxLayout()
        self.buttons_area.setSpacing(10)
        self.buttons_area.setObjectName("buttons_area")
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons_area.addItem(spacerItem)
        self.push_button_accept = QtWidgets.QPushButton(criteria)
        self.push_button_accept.setMinimumSize(QtCore.QSize(100, 32))
        self.push_button_accept.setObjectName("push_button_accept")
        self.buttons_area.addWidget(self.push_button_accept)
        self.push_button_cancel = QtWidgets.QPushButton(criteria)
        self.push_button_cancel.setMinimumSize(QtCore.QSize(100, 32))
        self.push_button_cancel.setObjectName("push_button_cancel")
        self.buttons_area.addWidget(self.push_button_cancel)
        self.verticalLayout.addLayout(self.buttons_area)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(criteria)
        QtCore.QMetaObject.connectSlotsByName(criteria)

    def retranslateUi(self, criteria):
        _translate = QtCore.QCoreApplication.translate
        criteria.setWindowTitle(_translate("criteria", "Criteria"))
        self.criterion_label.setText(_translate("criteria", "Criterion"))
        self.condition_label.setText(_translate("criteria", "Condition"))
        self.value_label.setText(_translate("criteria", "Value"))
        self.sample_id_label.setText(_translate("criteria", "Sample ID"))
        self.condition_1.setItemText(0, _translate("criteria", "<< select >>"))
        self.condition_1.setItemText(1, _translate("criteria", "All"))
        self.condition_1.setItemText(2, _translate("criteria", "Value"))
        self.process_idlabel.setText(_translate("criteria", "Process ID"))
        self.condition_2.setItemText(0, _translate("criteria", "<< select >>"))
        self.condition_2.setItemText(1, _translate("criteria", "All"))
        self.condition_2.setItemText(2, _translate("criteria", "Value"))
        self.data_type_label.setText(_translate("criteria", "Data Type"))
        self.condition_3.setItemText(0, _translate("criteria", "<< select >>"))
        self.condition_3.setItemText(1, _translate("criteria", "Same"))
        self.condition_3.setItemText(2, _translate("criteria", "Value"))
        self.push_button_accept.setText(_translate("criteria", "Accept"))
        self.push_button_accept.setShortcut(_translate("criteria", "Return"))
        self.push_button_cancel.setText(_translate("criteria", "Cancel"))
        self.push_button_cancel.setShortcut(_translate("criteria", "Esc"))

