# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/krl1to5/Work/FULL/Sequence-ToolKit/2016/resources/ui/dialogs/about/about.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_about(object):
    def setupUi(self, about):
        about.setObjectName("about")
        about.setWindowModality(QtCore.Qt.WindowModal)
        about.resize(800, 238)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(about.sizePolicy().hasHeightForWidth())
        about.setSizePolicy(sizePolicy)
        about.setMinimumSize(QtCore.QSize(666, 0))
        about.setMaximumSize(QtCore.QSize(9999999, 9999999))
        self.verticalLayout = QtWidgets.QVBoxLayout(about)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(about)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.app_icon = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app_icon.sizePolicy().hasHeightForWidth())
        self.app_icon.setSizePolicy(sizePolicy)
        self.app_icon.setMinimumSize(QtCore.QSize(150, 150))
        self.app_icon.setMaximumSize(QtCore.QSize(150, 150))
        self.app_icon.setText("")
        self.app_icon.setScaledContents(True)
        self.app_icon.setObjectName("app_icon")
        self.horizontalLayout.addWidget(self.app_icon)
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.setObjectName("layout")
        self.app_name = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.app_name.setFont(font)
        self.app_name.setStyleSheet("font-size:30px;\n"
"font-weight:bold")
        self.app_name.setObjectName("app_name")
        self.layout.addWidget(self.app_name)
        self.identity_layout = QtWidgets.QVBoxLayout()
        self.identity_layout.setSpacing(0)
        self.identity_layout.setObjectName("identity_layout")
        self.short_description = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.short_description.setFont(font)
        self.short_description.setStyleSheet("font-size:22px")
        self.short_description.setObjectName("short_description")
        self.identity_layout.addWidget(self.short_description)
        self.version = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.version.setFont(font)
        self.version.setStyleSheet("font-size:20px")
        self.version.setObjectName("version")
        self.identity_layout.addWidget(self.version)
        self.layout.addLayout(self.identity_layout)
        self.long_description = QtWidgets.QTextEdit(self.widget)
        self.long_description.setEnabled(True)
        self.long_description.setMinimumSize(QtCore.QSize(490, 70))
        self.long_description.setMaximumSize(QtCore.QSize(999999, 999999))
        self.long_description.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.long_description.setStyleSheet("background:transparent;\n"
"font-size:14px")
        self.long_description.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.long_description.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.long_description.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.long_description.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.long_description.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.long_description.setObjectName("long_description")
        self.layout.addWidget(self.long_description)
        self.horizontalLayout.addLayout(self.layout)
        self.verticalLayout.addWidget(self.widget)
        self.about_buttons_area = QtWidgets.QFrame(about)
        self.about_buttons_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.about_buttons_area.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.about_buttons_area.setLineWidth(0)
        self.about_buttons_area.setObjectName("about_buttons_area")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.about_buttons_area)
        self.horizontalLayout_2.setContentsMargins(0, 9, 0, 9)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.push_button_license = QtWidgets.QPushButton(self.about_buttons_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_button_license.sizePolicy().hasHeightForWidth())
        self.push_button_license.setSizePolicy(sizePolicy)
        self.push_button_license.setMinimumSize(QtCore.QSize(196, 32))
        self.push_button_license.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.push_button_license.setObjectName("push_button_license")
        self.horizontalLayout_2.addWidget(self.push_button_license)
        spacerItem = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.push_button_contact = QtWidgets.QPushButton(self.about_buttons_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_button_contact.sizePolicy().hasHeightForWidth())
        self.push_button_contact.setSizePolicy(sizePolicy)
        self.push_button_contact.setMinimumSize(QtCore.QSize(196, 32))
        self.push_button_contact.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.push_button_contact.setObjectName("push_button_contact")
        self.horizontalLayout_2.addWidget(self.push_button_contact)
        spacerItem1 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.push_button_credits = QtWidgets.QPushButton(self.about_buttons_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_button_credits.sizePolicy().hasHeightForWidth())
        self.push_button_credits.setSizePolicy(sizePolicy)
        self.push_button_credits.setMinimumSize(QtCore.QSize(196, 32))
        self.push_button_credits.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.push_button_credits.setObjectName("push_button_credits")
        self.horizontalLayout_2.addWidget(self.push_button_credits)
        self.verticalLayout.addWidget(self.about_buttons_area)

        self.retranslateUi(about)
        QtCore.QMetaObject.connectSlotsByName(about)

    def retranslateUi(self, about):
        _translate = QtCore.QCoreApplication.translate
        about.setWindowTitle(_translate("about", "About"))
        self.app_name.setText(_translate("about", "AppName"))
        self.short_description.setText(_translate("about", "App Short Description"))
        self.version.setText(_translate("about", "version 1.0.0"))
        self.long_description.setHtml(_translate("about", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:11pt;\">This is a long description about the app, and what it does.</span></p></body></html>"))
        self.push_button_license.setText(_translate("about", "License Information"))
        self.push_button_contact.setText(_translate("about", "Contact the Developers"))
        self.push_button_credits.setText(_translate("about", "Credits"))

import img_rc
