# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/krl1to5/Work/FULL/Sequence-ToolKit/2016/resources/ui/gensec/gensec.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(775, 556)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/img/logos/gensec.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window.setWindowIcon(icon)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_widget = QtWidgets.QTabWidget(self.central_widget)
        self.tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_widget.setElideMode(QtCore.Qt.ElideRight)
        self.tab_widget.setDocumentMode(True)
        self.tab_widget.setTabsClosable(True)
        self.tab_widget.setMovable(True)
        self.tab_widget.setTabBarAutoHide(False)
        self.tab_widget.setObjectName("tab_widget")
        self.gridLayout.addWidget(self.tab_widget, 0, 0, 1, 1)
        main_window.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 775, 19))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_recent_files = QtWidgets.QMenu(self.menu_file)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/img/icons/open_recent.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_recent_files.setIcon(icon1)
        self.menu_recent_files.setObjectName("menu_recent_files")
        self.menu_edit = QtWidgets.QMenu(self.menubar)
        self.menu_edit.setObjectName("menu_edit")
        self.menu_options = QtWidgets.QMenu(self.menubar)
        self.menu_options.setObjectName("menu_options")
        self.menu_sequence_global = QtWidgets.QMenu(self.menu_options)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/img/icons/sequence_options.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_sequence_global.setIcon(icon2)
        self.menu_sequence_global.setObjectName("menu_sequence_global")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.standard_toolbar = QtWidgets.QToolBar(main_window)
        self.standard_toolbar.setObjectName("standard_toolbar")
        main_window.addToolBar(QtCore.Qt.TopToolBarArea, self.standard_toolbar)
        self.tools_toolbar = QtWidgets.QToolBar(main_window)
        self.tools_toolbar.setObjectName("tools_toolbar")
        main_window.addToolBar(QtCore.Qt.TopToolBarArea, self.tools_toolbar)
        self.applications_toolbar = QtWidgets.QToolBar(main_window)
        self.applications_toolbar.setObjectName("applications_toolbar")
        main_window.addToolBar(QtCore.Qt.TopToolBarArea, self.applications_toolbar)
        self.action_new = QtWidgets.QAction(main_window)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/img/icons/new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_new.setIcon(icon3)
        self.action_new.setObjectName("action_new")
        self.action_open = QtWidgets.QAction(main_window)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resources/img/icons/open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open.setIcon(icon4)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(main_window)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resources/img/icons/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save.setIcon(icon5)
        self.action_save.setObjectName("action_save")
        self.action_save_as = QtWidgets.QAction(main_window)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/resources/img/icons/save_as.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save_as.setIcon(icon6)
        self.action_save_as.setObjectName("action_save_as")
        self.action_save_all = QtWidgets.QAction(main_window)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/resources/img/icons/save_all.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save_all.setIcon(icon7)
        self.action_save_all.setObjectName("action_save_all")
        self.action_print = QtWidgets.QAction(main_window)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/resources/img/icons/print.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_print.setIcon(icon8)
        self.action_print.setObjectName("action_print")
        self.action_cut = QtWidgets.QAction(main_window)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/resources/img/icons/cut.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_cut.setIcon(icon9)
        self.action_cut.setObjectName("action_cut")
        self.action_copy = QtWidgets.QAction(main_window)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/resources/img/icons/copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_copy.setIcon(icon10)
        self.action_copy.setObjectName("action_copy")
        self.action_paste = QtWidgets.QAction(main_window)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/resources/img/icons/paste.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_paste.setIcon(icon11)
        self.action_paste.setObjectName("action_paste")
        self.action_help = QtWidgets.QAction(main_window)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/resources/img/icons/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_help.setIcon(icon12)
        self.action_help.setObjectName("action_help")
        self.action_about = QtWidgets.QAction(main_window)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/resources/img/icons/about.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about.setIcon(icon13)
        self.action_about.setObjectName("action_about")
        self.action_delete = QtWidgets.QAction(main_window)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/resources/img/icons/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_delete.setIcon(icon14)
        self.action_delete.setObjectName("action_delete")
        self.action_quit = QtWidgets.QAction(main_window)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/resources/img/icons/quit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_quit.setIcon(icon15)
        self.action_quit.setObjectName("action_quit")
        self.action_close = QtWidgets.QAction(main_window)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/resources/img/icons/close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_close.setIcon(icon16)
        self.action_close.setObjectName("action_close")
        self.action_clear_all = QtWidgets.QAction(main_window)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/resources/img/icons/delete_all.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_clear_all.setIcon(icon17)
        self.action_clear_all.setObjectName("action_clear_all")
        self.action_preview = QtWidgets.QAction(main_window)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/resources/img/icons/xml_preview.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_preview.setIcon(icon18)
        self.action_preview.setObjectName("action_preview")
        self.action_add_row = QtWidgets.QAction(main_window)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/resources/img/icons/add_row.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_row.setIcon(icon19)
        self.action_add_row.setObjectName("action_add_row")
        self.action_add_column = QtWidgets.QAction(main_window)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/resources/img/icons/add_column.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_column.setIcon(icon20)
        self.action_add_column.setObjectName("action_add_column")
        self.action_sort = QtWidgets.QAction(main_window)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/resources/img/icons/sort.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_sort.setIcon(icon21)
        self.action_sort.setObjectName("action_sort")
        self.action_name = QtWidgets.QAction(main_window)
        self.action_name.setObjectName("action_name")
        self.action_owner = QtWidgets.QAction(main_window)
        self.action_owner.setObjectName("action_owner")
        self.action_nitrogen_use = QtWidgets.QAction(main_window)
        self.action_nitrogen_use.setObjectName("action_nitrogen_use")
        self.action_dose_rate = QtWidgets.QAction(main_window)
        self.action_dose_rate.setObjectName("action_dose_rate")
        self.action_external_dose_rate = QtWidgets.QAction(main_window)
        self.action_external_dose_rate.setObjectName("action_external_dose_rate")
        self.action_protocol = QtWidgets.QAction(main_window)
        self.action_protocol.setObjectName("action_protocol")
        self.action_reader_id = QtWidgets.QAction(main_window)
        self.action_reader_id.setObjectName("action_reader_id")
        self.action_merge = QtWidgets.QAction(main_window)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/resources/img/icons/merge.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_merge.setIcon(icon22)
        self.action_merge.setObjectName("action_merge")
        self.action_split = QtWidgets.QAction(main_window)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/resources/img/icons/split.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_split.setIcon(icon23)
        self.action_split.setObjectName("action_split")
        self.action_reset = QtWidgets.QAction(main_window)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/resources/img/icons/reset.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_reset.setIcon(icon24)
        self.action_reset.setObjectName("action_reset")
        self.action_merge_colors = QtWidgets.QAction(main_window)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/resources/img/icons/colors.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_merge_colors.setIcon(icon25)
        self.action_merge_colors.setObjectName("action_merge_colors")
        self.action_about_gensec = QtWidgets.QAction(main_window)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/resources/img/icons/about_variant.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about_gensec.setIcon(icon26)
        self.action_about_gensec.setObjectName("action_about_gensec")
        self.action_settings = QtWidgets.QAction(main_window)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/resources/img/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_settings.setIcon(icon27)
        self.action_settings.setObjectName("action_settings")
        self.action_exec_genrep = QtWidgets.QAction(main_window)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/resources/img/logos/genrep.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exec_genrep.setIcon(icon28)
        self.action_exec_genrep.setObjectName("action_exec_genrep")
        self.action_undo = QtWidgets.QAction(main_window)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/resources/img/icons/undo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_undo.setIcon(icon29)
        self.action_undo.setObjectName("action_undo")
        self.action_redo = QtWidgets.QAction(main_window)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/resources/img/icons/redo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_redo.setIcon(icon30)
        self.action_redo.setObjectName("action_redo")
        self.action_exec_genvis = QtWidgets.QAction(main_window)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/resources/img/logos/genvis.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exec_genvis.setIcon(icon31)
        self.action_exec_genvis.setObjectName("action_exec_genvis")
        self.action_merge_by_criteria = QtWidgets.QAction(main_window)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/resources/img/icons/merge_by_criteria.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_merge_by_criteria.setIcon(icon32)
        self.action_merge_by_criteria.setObjectName("action_merge_by_criteria")
        self.action_split_by_criteria = QtWidgets.QAction(main_window)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/resources/img/icons/split_by_criteria.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_split_by_criteria.setIcon(icon33)
        self.action_split_by_criteria.setObjectName("action_split_by_criteria")
        self.menu_file.addAction(self.action_new)
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.menu_recent_files.menuAction())
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_save_as)
        self.menu_file.addAction(self.action_save_all)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_print)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_close)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_quit)
        self.menu_edit.addAction(self.action_undo)
        self.menu_edit.addAction(self.action_redo)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.action_cut)
        self.menu_edit.addAction(self.action_copy)
        self.menu_edit.addAction(self.action_paste)
        self.menu_edit.addAction(self.action_delete)
        self.menu_edit.addAction(self.action_clear_all)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.action_merge)
        self.menu_edit.addAction(self.action_split)
        self.menu_edit.addAction(self.action_merge_by_criteria)
        self.menu_edit.addAction(self.action_split_by_criteria)
        self.menu_edit.addAction(self.action_reset)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.action_add_row)
        self.menu_edit.addAction(self.action_add_column)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.action_sort)
        self.menu_sequence_global.addAction(self.action_name)
        self.menu_sequence_global.addAction(self.action_owner)
        self.menu_sequence_global.addAction(self.action_nitrogen_use)
        self.menu_sequence_global.addAction(self.action_dose_rate)
        self.menu_sequence_global.addAction(self.action_external_dose_rate)
        self.menu_sequence_global.addAction(self.action_protocol)
        self.menu_sequence_global.addAction(self.action_reader_id)
        self.menu_options.addAction(self.menu_sequence_global.menuAction())
        self.menu_options.addAction(self.action_merge_colors)
        self.menu_options.addSeparator()
        self.menu_options.addAction(self.action_preview)
        self.menu_options.addSeparator()
        self.menu_options.addAction(self.action_settings)
        self.menu_help.addAction(self.action_help)
        self.menu_help.addSeparator()
        self.menu_help.addAction(self.action_about_gensec)
        self.menu_help.addAction(self.action_about)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu_options.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.standard_toolbar.addAction(self.action_new)
        self.standard_toolbar.addAction(self.action_open)
        self.standard_toolbar.addAction(self.action_save)
        self.standard_toolbar.addAction(self.action_preview)
        self.standard_toolbar.addAction(self.action_print)
        self.tools_toolbar.addAction(self.action_merge)
        self.tools_toolbar.addAction(self.action_split)
        self.tools_toolbar.addAction(self.action_reset)
        self.applications_toolbar.addAction(self.action_exec_genrep)
        self.applications_toolbar.addAction(self.action_exec_genvis)

        self.retranslateUi(main_window)
        self.tab_widget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "GenSec"))
        self.menu_file.setTitle(_translate("main_window", "&File"))
        self.menu_recent_files.setTitle(_translate("main_window", "&Recent Files"))
        self.menu_edit.setTitle(_translate("main_window", "&Edit"))
        self.menu_options.setTitle(_translate("main_window", "&Options"))
        self.menu_sequence_global.setTitle(_translate("main_window", "Sequence &Global"))
        self.menu_help.setTitle(_translate("main_window", "&Help"))
        self.standard_toolbar.setWindowTitle(_translate("main_window", "Standard Bar"))
        self.tools_toolbar.setWindowTitle(_translate("main_window", "Tools Bar"))
        self.applications_toolbar.setWindowTitle(_translate("main_window", "Applications Bar"))
        self.action_new.setText(_translate("main_window", "&New"))
        self.action_new.setStatusTip(_translate("main_window", "Create a new file."))
        self.action_new.setShortcut(_translate("main_window", "Ctrl+N"))
        self.action_open.setText(_translate("main_window", "&Open"))
        self.action_open.setStatusTip(_translate("main_window", "Open an existing file."))
        self.action_open.setShortcut(_translate("main_window", "Ctrl+O"))
        self.action_save.setText(_translate("main_window", "&Save"))
        self.action_save.setStatusTip(_translate("main_window", "Save the current document on disk."))
        self.action_save.setShortcut(_translate("main_window", "Ctrl+S"))
        self.action_save_as.setText(_translate("main_window", "Save &As"))
        self.action_save_as.setStatusTip(_translate("main_window", "Save the current document under a new name."))
        self.action_save_as.setShortcut(_translate("main_window", "Ctrl+Shift+S"))
        self.action_save_all.setText(_translate("main_window", "Save A&ll"))
        self.action_save_all.setStatusTip(_translate("main_window", "Save all documents on disk."))
        self.action_print.setText(_translate("main_window", "&Print"))
        self.action_print.setStatusTip(_translate("main_window", "Print the current table."))
        self.action_print.setShortcut(_translate("main_window", "Ctrl+P"))
        self.action_cut.setText(_translate("main_window", "C&ut"))
        self.action_cut.setStatusTip(_translate("main_window", "Cut the current selection content to the clipboard."))
        self.action_cut.setShortcut(_translate("main_window", "Ctrl+X"))
        self.action_copy.setText(_translate("main_window", "&Copy"))
        self.action_copy.setStatusTip(_translate("main_window", "Copy the current selection content to the clipboard."))
        self.action_copy.setShortcut(_translate("main_window", "Ctrl+C"))
        self.action_paste.setText(_translate("main_window", "&Paste"))
        self.action_paste.setStatusTip(_translate("main_window", "Paste the clipboard content into the current selection."))
        self.action_paste.setShortcut(_translate("main_window", "Ctrl+V"))
        self.action_help.setText(_translate("main_window", "&Help"))
        self.action_help.setShortcut(_translate("main_window", "F1"))
        self.action_about.setText(_translate("main_window", "About &Sequence-ToolKit"))
        self.action_delete.setText(_translate("main_window", "&Delete"))
        self.action_delete.setStatusTip(_translate("main_window", "Remove the current selection."))
        self.action_delete.setShortcut(_translate("main_window", "Del"))
        self.action_quit.setText(_translate("main_window", "&Quit"))
        self.action_quit.setStatusTip(_translate("main_window", "Close all tabs and quit the application."))
        self.action_quit.setShortcut(_translate("main_window", "Ctrl+Q"))
        self.action_close.setText(_translate("main_window", "&Close"))
        self.action_close.setStatusTip(_translate("main_window", "Close the current tab."))
        self.action_close.setShortcut(_translate("main_window", "Ctrl+W"))
        self.action_clear_all.setText(_translate("main_window", "C&lear All"))
        self.action_clear_all.setStatusTip(_translate("main_window", "Delete all the content of the table."))
        self.action_clear_all.setShortcut(_translate("main_window", "Shift+Del"))
        self.action_preview.setText(_translate("main_window", "XML &Preview"))
        self.action_preview.setStatusTip(_translate("main_window", "Open a preview of the xml file."))
        self.action_preview.setShortcut(_translate("main_window", "Ctrl+U"))
        self.action_add_row.setText(_translate("main_window", "Add Ro&w"))
        self.action_add_row.setStatusTip(_translate("main_window", "Add one row at end of the table."))
        self.action_add_row.setShortcut(_translate("main_window", "F9"))
        self.action_add_column.setText(_translate("main_window", "&Add Column"))
        self.action_add_column.setStatusTip(_translate("main_window", "Add one column at end of the table."))
        self.action_add_column.setShortcut(_translate("main_window", "F10"))
        self.action_sort.setText(_translate("main_window", "S&ort Rows"))
        self.action_sort.setStatusTip(_translate("main_window", "Sorts the contents of the table by the number of samples."))
        self.action_sort.setShortcut(_translate("main_window", "Ctrl+Space"))
        self.action_name.setText(_translate("main_window", "&Name"))
        self.action_name.setStatusTip(_translate("main_window", "Change the sequence\'s name."))
        self.action_owner.setText(_translate("main_window", "&Owner"))
        self.action_owner.setStatusTip(_translate("main_window", "Change the name of the sequence\'s owner."))
        self.action_nitrogen_use.setText(_translate("main_window", "Nitro&gen Use"))
        self.action_nitrogen_use.setStatusTip(_translate("main_window", "Change the use of nitrogen in the sequence."))
        self.action_dose_rate.setText(_translate("main_window", "&Dose Rate"))
        self.action_dose_rate.setStatusTip(_translate("main_window", "Change the dose rate of the sequence."))
        self.action_external_dose_rate.setText(_translate("main_window", "&External Dose Rate"))
        self.action_external_dose_rate.setStatusTip(_translate("main_window", "Change the external dose rate of the sequence."))
        self.action_protocol.setText(_translate("main_window", "&Protocol"))
        self.action_protocol.setStatusTip(_translate("main_window", "Change the protocol of the sequence."))
        self.action_reader_id.setText(_translate("main_window", "&Reader ID"))
        self.action_reader_id.setStatusTip(_translate("main_window", "Show the sequence\'s  reader id."))
        self.action_merge.setText(_translate("main_window", "&Merge"))
        self.action_merge.setStatusTip(_translate("main_window", "Merge several commands in the same process order."))
        self.action_merge.setShortcut(_translate("main_window", "Ctrl+M"))
        self.action_split.setText(_translate("main_window", "&Split"))
        self.action_split.setStatusTip(_translate("main_window", "Split the selected merges."))
        self.action_split.setShortcut(_translate("main_window", "Ctrl+I"))
        self.action_reset.setText(_translate("main_window", "&Reset"))
        self.action_reset.setStatusTip(_translate("main_window", "Set all states to \'pend\', clean all \'data\' tags of all process and restores name, date-creation and reader ID of the sequence."))
        self.action_reset.setShortcut(_translate("main_window", "Ctrl+R"))
        self.action_merge_colors.setText(_translate("main_window", "&Merge Colors"))
        self.action_about_gensec.setText(_translate("main_window", "About &GenSec"))
        self.action_settings.setText(_translate("main_window", "&Settings"))
        self.action_exec_genrep.setText(_translate("main_window", "GenRep"))
        self.action_exec_genrep.setToolTip(_translate("main_window", "Open Report Generator"))
        self.action_undo.setText(_translate("main_window", "Undo"))
        self.action_undo.setShortcut(_translate("main_window", "Ctrl+Z"))
        self.action_redo.setText(_translate("main_window", "Redo"))
        self.action_redo.setShortcut(_translate("main_window", "Ctrl+Shift+Z"))
        self.action_exec_genvis.setText(_translate("main_window", "GenVis"))
        self.action_exec_genvis.setToolTip(_translate("main_window", "Open Report Analyzer"))
        self.action_merge_by_criteria.setText(_translate("main_window", "Merge by Criteria"))
        self.action_merge_by_criteria.setToolTip(_translate("main_window", "Merge by Criteria"))
        self.action_merge_by_criteria.setStatusTip(_translate("main_window", "Merge several commands in the same process order."))
        self.action_merge_by_criteria.setShortcut(_translate("main_window", "Ctrl+Shift+M"))
        self.action_split_by_criteria.setText(_translate("main_window", "Split by Criteria"))
        self.action_split_by_criteria.setToolTip(_translate("main_window", "Split by Criteria"))
        self.action_split_by_criteria.setStatusTip(_translate("main_window", "Split the selected merges."))
        self.action_split_by_criteria.setShortcut(_translate("main_window", "Ctrl+Shift+I"))

import img_rc
