# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/krl1to5/Work/FULL/Sequence-ToolKit/2016/resources/ui/stk/stk.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_stk(object):
    def setupUi(self, stk):
        stk.setObjectName("stk")
        stk.resize(987, 1344)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/img/logos/sequence_toolkit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        stk.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(stk)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stk_left_panel = QtWidgets.QFrame(self.centralwidget)
        self.stk_left_panel.setMinimumSize(QtCore.QSize(300, 0))
        self.stk_left_panel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stk_left_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stk_left_panel.setObjectName("stk_left_panel")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.stk_left_panel)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.push_button_open_file = QtWidgets.QPushButton(self.stk_left_panel)
        self.push_button_open_file.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.push_button_open_file.setFont(font)
        self.push_button_open_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_button_open_file.setStyleSheet("text-align: left")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/img/icons/open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_button_open_file.setIcon(icon1)
        self.push_button_open_file.setIconSize(QtCore.QSize(30, 30))
        self.push_button_open_file.setObjectName("push_button_open_file")
        self.gridLayout_2.addWidget(self.push_button_open_file, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.stk_left_panel)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.setSpacing(0)
        self.layout.setObjectName("layout")
        self.push_button_gensec = QtWidgets.QPushButton(self.stk_left_panel)
        self.push_button_gensec.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.push_button_gensec.setFont(font)
        self.push_button_gensec.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_button_gensec.setStyleSheet("text-align: left")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/img/logos/gensec.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_button_gensec.setIcon(icon2)
        self.push_button_gensec.setIconSize(QtCore.QSize(30, 30))
        self.push_button_gensec.setObjectName("push_button_gensec")
        self.layout.addWidget(self.push_button_gensec)
        self.push_button_genrep = QtWidgets.QPushButton(self.stk_left_panel)
        self.push_button_genrep.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.push_button_genrep.setFont(font)
        self.push_button_genrep.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_button_genrep.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.push_button_genrep.setStyleSheet("text-align: left")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/img/logos/genrep.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_button_genrep.setIcon(icon3)
        self.push_button_genrep.setIconSize(QtCore.QSize(30, 30))
        self.push_button_genrep.setObjectName("push_button_genrep")
        self.layout.addWidget(self.push_button_genrep)
        self.push_button_genvis = QtWidgets.QPushButton(self.stk_left_panel)
        self.push_button_genvis.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.push_button_genvis.setFont(font)
        self.push_button_genvis.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_button_genvis.setStyleSheet("text-align: left")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resources/img/logos/genvis.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_button_genvis.setIcon(icon4)
        self.push_button_genvis.setIconSize(QtCore.QSize(30, 30))
        self.push_button_genvis.setObjectName("push_button_genvis")
        self.layout.addWidget(self.push_button_genvis)
        self.gridLayout_2.addLayout(self.layout, 2, 0, 1, 1)
        self.background_image = QtWidgets.QLabel(self.stk_left_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background_image.sizePolicy().hasHeightForWidth())
        self.background_image.setSizePolicy(sizePolicy)
        self.background_image.setText("")
        self.background_image.setObjectName("background_image")
        self.gridLayout_2.addWidget(self.background_image, 3, 0, 1, 1)
        self.layout_2 = QtWidgets.QHBoxLayout()
        self.layout_2.setSpacing(20)
        self.layout_2.setObjectName("layout_2")
        self.push_button_settings = QtWidgets.QPushButton(self.stk_left_panel)
        self.push_button_settings.setMinimumSize(QtCore.QSize(0, 32))
        self.push_button_settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_button_settings.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resources/img/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_button_settings.setIcon(icon5)
        self.push_button_settings.setIconSize(QtCore.QSize(32, 32))
        self.push_button_settings.setObjectName("push_button_settings")
        self.layout_2.addWidget(self.push_button_settings)
        self.push_button_help = QtWidgets.QPushButton(self.stk_left_panel)
        self.push_button_help.setMinimumSize(QtCore.QSize(0, 32))
        self.push_button_help.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_button_help.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/resources/img/icons/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_button_help.setIcon(icon6)
        self.push_button_help.setIconSize(QtCore.QSize(32, 32))
        self.push_button_help.setObjectName("push_button_help")
        self.layout_2.addWidget(self.push_button_help)
        self.push_button_about = QtWidgets.QPushButton(self.stk_left_panel)
        self.push_button_about.setMinimumSize(QtCore.QSize(0, 32))
        self.push_button_about.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.push_button_about.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/resources/img/icons/about.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_button_about.setIcon(icon7)
        self.push_button_about.setIconSize(QtCore.QSize(32, 32))
        self.push_button_about.setObjectName("push_button_about")
        self.layout_2.addWidget(self.push_button_about)
        self.gridLayout_2.addLayout(self.layout_2, 4, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.stk_left_panel)
        self.stk_right_area = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stk_right_area.sizePolicy().hasHeightForWidth())
        self.stk_right_area.setSizePolicy(sizePolicy)
        self.stk_right_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stk_right_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stk_right_area.setObjectName("stk_right_area")
        self.gridLayout = QtWidgets.QGridLayout(self.stk_right_area)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scroll_area = QtWidgets.QScrollArea(self.stk_right_area)
        self.scroll_area.setMouseTracking(True)
        self.scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_area.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scroll_area.setLineWidth(0)
        self.scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_area_contents = QtWidgets.QWidget()
        self.scroll_area_contents.setGeometry(QtCore.QRect(0, 0, 687, 1322))
        self.scroll_area_contents.setObjectName("scroll_area_contents")
        self.scroll_area_layout = QtWidgets.QVBoxLayout(self.scroll_area_contents)
        self.scroll_area_layout.setContentsMargins(0, 0, 0, 0)
        self.scroll_area_layout.setSpacing(0)
        self.scroll_area_layout.setObjectName("scroll_area_layout")
        self.scroll_area.setWidget(self.scroll_area_contents)
        self.gridLayout.addWidget(self.scroll_area, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.stk_right_area)
        stk.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(stk)
        self.statusbar.setObjectName("statusbar")
        stk.setStatusBar(self.statusbar)

        self.retranslateUi(stk)
        QtCore.QMetaObject.connectSlotsByName(stk)

    def retranslateUi(self, stk):
        _translate = QtCore.QCoreApplication.translate
        stk.setWindowTitle(_translate("stk", "Sequence-ToolKit"))
        self.push_button_open_file.setText(_translate("stk", "Open File"))
        self.push_button_gensec.setText(_translate("stk", "Open GenSec"))
        self.push_button_genrep.setText(_translate("stk", "Open GenRep"))
        self.push_button_genvis.setText(_translate("stk", "Open GenVis"))
        self.push_button_settings.setToolTip(_translate("stk", "Settings"))
        self.push_button_help.setToolTip(_translate("stk", "Help"))
        self.push_button_about.setToolTip(_translate("stk", "About"))

import img_rc
