# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/krl1to5/Work/FULL/Sequence-ToolKit/2016/resources/ui/gensec/process/illumination.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_process(object):
    def setupUi(self, process):
        process.setObjectName("process")
        process.resize(603, 164)
        process.setMinimumSize(QtCore.QSize(0, 164))
        process.setMaximumSize(QtCore.QSize(16777215, 164))
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(process)
        self.horizontalLayout_6.setSpacing(12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.form_area = QtWidgets.QFrame(process)
        self.form_area.setFrameShape(QtWidgets.QFrame.Box)
        self.form_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.form_area.setObjectName("form_area")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.form_area)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.setSpacing(12)
        self.layout.setObjectName("layout")
        self.layout_2 = QtWidgets.QHBoxLayout()
        self.layout_2.setObjectName("layout_2")
        self.final_temperature_label = QtWidgets.QLabel(self.form_area)
        self.final_temperature_label.setObjectName("final_temperature_label")
        self.layout_2.addWidget(self.final_temperature_label)
        self.final_temperature = QtWidgets.QDoubleSpinBox(self.form_area)
        self.final_temperature.setMinimumSize(QtCore.QSize(80, 28))
        self.final_temperature.setMaximumSize(QtCore.QSize(80, 16777215))
        self.final_temperature.setMaximum(600.0)
        self.final_temperature.setObjectName("final_temperature")
        self.layout_2.addWidget(self.final_temperature)
        self.layout.addLayout(self.layout_2)
        self.layout_3 = QtWidgets.QHBoxLayout()
        self.layout_3.setObjectName("layout_3")
        self.heating_rate_label = QtWidgets.QLabel(self.form_area)
        self.heating_rate_label.setObjectName("heating_rate_label")
        self.layout_3.addWidget(self.heating_rate_label)
        self.heating_rate = QtWidgets.QDoubleSpinBox(self.form_area)
        self.heating_rate.setMinimumSize(QtCore.QSize(80, 28))
        self.heating_rate.setMaximumSize(QtCore.QSize(80, 16777215))
        self.heating_rate.setMinimum(0.1)
        self.heating_rate.setMaximum(20.0)
        self.heating_rate.setObjectName("heating_rate")
        self.layout_3.addWidget(self.heating_rate)
        self.layout.addLayout(self.layout_3)
        self.layout_4 = QtWidgets.QHBoxLayout()
        self.layout_4.setObjectName("layout_4")
        self.stabilization_label = QtWidgets.QLabel(self.form_area)
        self.stabilization_label.setObjectName("stabilization_label")
        self.layout_4.addWidget(self.stabilization_label)
        self.stabilization = QtWidgets.QDoubleSpinBox(self.form_area)
        self.stabilization.setMinimumSize(QtCore.QSize(80, 28))
        self.stabilization.setMaximumSize(QtCore.QSize(80, 16777215))
        self.stabilization.setMaximum(99999.0)
        self.stabilization.setObjectName("stabilization")
        self.layout_4.addWidget(self.stabilization)
        self.layout.addLayout(self.layout_4)
        self.horizontalLayout_3.addLayout(self.layout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.line = QtWidgets.QFrame(self.form_area)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.layout_5 = QtWidgets.QVBoxLayout()
        self.layout_5.setContentsMargins(-1, -1, -1, 0)
        self.layout_5.setSpacing(12)
        self.layout_5.setObjectName("layout_5")
        self.layout_6 = QtWidgets.QHBoxLayout()
        self.layout_6.setObjectName("layout_6")
        self.optical_power_label = QtWidgets.QLabel(self.form_area)
        self.optical_power_label.setObjectName("optical_power_label")
        self.layout_6.addWidget(self.optical_power_label)
        self.optical_power = QtWidgets.QSpinBox(self.form_area)
        self.optical_power.setMinimumSize(QtCore.QSize(55, 28))
        self.optical_power.setMaximumSize(QtCore.QSize(55, 16777215))
        self.optical_power.setMaximum(100)
        self.optical_power.setObjectName("optical_power")
        self.layout_6.addWidget(self.optical_power)
        self.layout_5.addLayout(self.layout_6)
        self.layout_7 = QtWidgets.QHBoxLayout()
        self.layout_7.setObjectName("layout_7")
        self.ligth_source_label = QtWidgets.QLabel(self.form_area)
        self.ligth_source_label.setObjectName("ligth_source_label")
        self.layout_7.addWidget(self.ligth_source_label)
        self.ligth_source = QtWidgets.QComboBox(self.form_area)
        self.ligth_source.setMinimumSize(QtCore.QSize(58, 28))
        self.ligth_source.setMaximumSize(QtCore.QSize(58, 16777215))
        self.ligth_source.setObjectName("ligth_source")
        self.ligth_source.addItem("")
        self.ligth_source.addItem("")
        self.ligth_source.addItem("")
        self.layout_7.addWidget(self.ligth_source)
        self.layout_5.addLayout(self.layout_7)
        self.layout_8 = QtWidgets.QHBoxLayout()
        self.layout_8.setObjectName("layout_8")
        self.time_label = QtWidgets.QLabel(self.form_area)
        self.time_label.setObjectName("time_label")
        self.layout_8.addWidget(self.time_label)
        self.time = QtWidgets.QDoubleSpinBox(self.form_area)
        self.time.setMinimumSize(QtCore.QSize(80, 28))
        self.time.setMaximumSize(QtCore.QSize(80, 16777215))
        self.time.setMaximum(99999.0)
        self.time.setObjectName("time")
        self.layout_8.addWidget(self.time)
        self.layout_5.addLayout(self.layout_8)
        self.horizontalLayout_3.addLayout(self.layout_5)
        self.horizontalLayout_6.addWidget(self.form_area)
        self.button_area = QtWidgets.QFrame(process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_area.sizePolicy().hasHeightForWidth())
        self.button_area.setSizePolicy(sizePolicy)
        self.button_area.setMinimumSize(QtCore.QSize(0, 0))
        self.button_area.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_area.setFrameShape(QtWidgets.QFrame.Box)
        self.button_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_area.setObjectName("button_area")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.button_area)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.push_button_accept = QtWidgets.QPushButton(self.button_area)
        self.push_button_accept.setMinimumSize(QtCore.QSize(100, 32))
        self.push_button_accept.setShortcut("Return")
        self.push_button_accept.setObjectName("push_button_accept")
        self.verticalLayout_3.addWidget(self.push_button_accept)
        self.push_button_cancel = QtWidgets.QPushButton(self.button_area)
        self.push_button_cancel.setMinimumSize(QtCore.QSize(100, 32))
        self.push_button_cancel.setShortcut("Esc")
        self.push_button_cancel.setObjectName("push_button_cancel")
        self.verticalLayout_3.addWidget(self.push_button_cancel)
        self.push_button_information = QtWidgets.QPushButton(self.button_area)
        self.push_button_information.setMinimumSize(QtCore.QSize(100, 32))
        self.push_button_information.setObjectName("push_button_information")
        self.verticalLayout_3.addWidget(self.push_button_information)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_6.addWidget(self.button_area)

        self.retranslateUi(process)
        QtCore.QMetaObject.connectSlotsByName(process)

    def retranslateUi(self, process):
        _translate = QtCore.QCoreApplication.translate
        process.setWindowTitle(_translate("process", "Illumination"))
        self.final_temperature_label.setText(_translate("process", "Final Temperature (°C)"))
        self.heating_rate_label.setText(_translate("process", "Heating Rate (°C/s)"))
        self.stabilization_label.setText(_translate("process", "Stabilization (s)"))
        self.optical_power_label.setText(_translate("process", "Optical Power (%)"))
        self.ligth_source_label.setText(_translate("process", "Ligth Source"))
        self.ligth_source.setItemText(0, _translate("process", "Blue"))
        self.ligth_source.setItemText(1, _translate("process", "IR"))
        self.ligth_source.setItemText(2, _translate("process", "AUX"))
        self.time_label.setText(_translate("process", "Time (s)"))
        self.push_button_accept.setText(_translate("process", "Accept"))
        self.push_button_cancel.setText(_translate("process", "Cancel"))
        self.push_button_information.setText(_translate("process", "Information"))

