# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/krl1to5/Work/FULL/Sequence-ToolKit/2016/resources/ui/gensec/process/pre_heat.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_process(object):
    def setupUi(self, process):
        process.setObjectName("process")
        process.resize(427, 164)
        process.setMinimumSize(QtCore.QSize(0, 164))
        process.setMaximumSize(QtCore.QSize(16777215, 164))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(process)
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.form_area = QtWidgets.QFrame(process)
        self.form_area.setFrameShape(QtWidgets.QFrame.Box)
        self.form_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.form_area.setObjectName("form_area")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.form_area)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout = QtWidgets.QHBoxLayout()
        self.layout.setObjectName("layout")
        self.final_temperature_label = QtWidgets.QLabel(self.form_area)
        self.final_temperature_label.setObjectName("final_temperature_label")
        self.layout.addWidget(self.final_temperature_label)
        self.final_temperature = QtWidgets.QDoubleSpinBox(self.form_area)
        self.final_temperature.setMinimumSize(QtCore.QSize(80, 28))
        self.final_temperature.setMaximumSize(QtCore.QSize(80, 16777215))
        self.final_temperature.setMaximum(600.0)
        self.final_temperature.setObjectName("final_temperature")
        self.layout.addWidget(self.final_temperature)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.layout)
        self.layout_2 = QtWidgets.QHBoxLayout()
        self.layout_2.setObjectName("layout_2")
        self.time_at_final_temp_label = QtWidgets.QLabel(self.form_area)
        self.time_at_final_temp_label.setObjectName("time_at_final_temp_label")
        self.layout_2.addWidget(self.time_at_final_temp_label)
        self.time_at_final_temp = QtWidgets.QDoubleSpinBox(self.form_area)
        self.time_at_final_temp.setMinimumSize(QtCore.QSize(80, 28))
        self.time_at_final_temp.setMaximumSize(QtCore.QSize(80, 16777215))
        self.time_at_final_temp.setMaximum(99999.0)
        self.time_at_final_temp.setObjectName("time_at_final_temp")
        self.layout_2.addWidget(self.time_at_final_temp)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.layout_2)
        self.layout_3 = QtWidgets.QHBoxLayout()
        self.layout_3.setObjectName("layout_3")
        self.heating_rate_label = QtWidgets.QLabel(self.form_area)
        self.heating_rate_label.setObjectName("heating_rate_label")
        self.layout_3.addWidget(self.heating_rate_label)
        self.heating_rate = QtWidgets.QDoubleSpinBox(self.form_area)
        self.heating_rate.setMinimumSize(QtCore.QSize(80, 28))
        self.heating_rate.setMaximumSize(QtCore.QSize(80, 16777215))
        self.heating_rate.setMinimum(0.1)
        self.heating_rate.setMaximum(20.0)
        self.heating_rate.setObjectName("heating_rate")
        self.layout_3.addWidget(self.heating_rate)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.layout_3)
        self.horizontalLayout_3.addWidget(self.form_area)
        self.frame_2 = QtWidgets.QFrame(process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.push_button_accept = QtWidgets.QPushButton(self.frame_2)
        self.push_button_accept.setMinimumSize(QtCore.QSize(100, 32))
        self.push_button_accept.setShortcut("Return")
        self.push_button_accept.setObjectName("push_button_accept")
        self.verticalLayout_2.addWidget(self.push_button_accept)
        self.push_button_cancel = QtWidgets.QPushButton(self.frame_2)
        self.push_button_cancel.setMinimumSize(QtCore.QSize(100, 32))
        self.push_button_cancel.setShortcut("Esc")
        self.push_button_cancel.setObjectName("push_button_cancel")
        self.verticalLayout_2.addWidget(self.push_button_cancel)
        self.push_button_information = QtWidgets.QPushButton(self.frame_2)
        self.push_button_information.setMinimumSize(QtCore.QSize(100, 32))
        self.push_button_information.setObjectName("push_button_information")
        self.verticalLayout_2.addWidget(self.push_button_information)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_3.addWidget(self.frame_2)

        self.retranslateUi(process)
        QtCore.QMetaObject.connectSlotsByName(process)

    def retranslateUi(self, process):
        _translate = QtCore.QCoreApplication.translate
        process.setWindowTitle(_translate("process", "Pre Heat"))
        self.final_temperature_label.setText(_translate("process", "Final Temperature (°C)"))
        self.time_at_final_temp_label.setText(_translate("process", "Time at final temperature (s)"))
        self.heating_rate_label.setText(_translate("process", "Heating Rate (°C/s)"))
        self.push_button_accept.setText(_translate("process", "Accept"))
        self.push_button_cancel.setText(_translate("process", "Cancel"))
        self.push_button_information.setText(_translate("process", "Information"))

