# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/krl1to5/Work/FULL/Sequence-ToolKit/2016/resources/ui/gensec/process/tl.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_process(object):
    def setupUi(self, process):
        process.setObjectName("process")
        process.resize(680, 164)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(process.sizePolicy().hasHeightForWidth())
        process.setSizePolicy(sizePolicy)
        process.setMinimumSize(QtCore.QSize(0, 164))
        process.setMaximumSize(QtCore.QSize(16777215, 164))
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(process)
        self.horizontalLayout_8.setSpacing(12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.form_area = QtWidgets.QFrame(process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.form_area.sizePolicy().hasHeightForWidth())
        self.form_area.setSizePolicy(sizePolicy)
        self.form_area.setFrameShape(QtWidgets.QFrame.Box)
        self.form_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.form_area.setObjectName("form_area")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.form_area)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout = QtWidgets.QHBoxLayout()
        self.layout.setSpacing(15)
        self.layout.setObjectName("layout")
        self.layout_2 = QtWidgets.QHBoxLayout()
        self.layout_2.setObjectName("layout_2")
        self.final_temperature_label = QtWidgets.QLabel(self.form_area)
        self.final_temperature_label.setObjectName("final_temperature_label")
        self.layout_2.addWidget(self.final_temperature_label)
        self.final_temperature = QtWidgets.QDoubleSpinBox(self.form_area)
        self.final_temperature.setMinimumSize(QtCore.QSize(80, 28))
        self.final_temperature.setMaximumSize(QtCore.QSize(80, 16777215))
        self.final_temperature.setMaximum(600.0)
        self.final_temperature.setObjectName("final_temperature")
        self.layout_2.addWidget(self.final_temperature)
        self.layout.addLayout(self.layout_2)
        self.layout_3 = QtWidgets.QHBoxLayout()
        self.layout_3.setObjectName("layout_3")
        self.time_at_final_temp_label = QtWidgets.QLabel(self.form_area)
        self.time_at_final_temp_label.setObjectName("time_at_final_temp_label")
        self.layout_3.addWidget(self.time_at_final_temp_label)
        self.time_at_final_temp = QtWidgets.QDoubleSpinBox(self.form_area)
        self.time_at_final_temp.setMinimumSize(QtCore.QSize(80, 28))
        self.time_at_final_temp.setMaximumSize(QtCore.QSize(80, 16777215))
        self.time_at_final_temp.setMaximum(99999.0)
        self.time_at_final_temp.setObjectName("time_at_final_temp")
        self.layout_3.addWidget(self.time_at_final_temp)
        self.layout.addLayout(self.layout_3)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.layout)
        self.layout_4 = QtWidgets.QHBoxLayout()
        self.layout_4.setSpacing(15)
        self.layout_4.setObjectName("layout_4")
        self.layout_5 = QtWidgets.QHBoxLayout()
        self.layout_5.setObjectName("layout_5")
        self.channels_label = QtWidgets.QLabel(self.form_area)
        self.channels_label.setObjectName("channels_label")
        self.layout_5.addWidget(self.channels_label)
        self.channels = QtWidgets.QSpinBox(self.form_area)
        self.channels.setMinimumSize(QtCore.QSize(55, 28))
        self.channels.setMaximumSize(QtCore.QSize(55, 16777215))
        self.channels.setMaximum(512)
        self.channels.setObjectName("channels")
        self.layout_5.addWidget(self.channels)
        self.layout_4.addLayout(self.layout_5)
        self.layout_6 = QtWidgets.QHBoxLayout()
        self.layout_6.setObjectName("layout_6")
        self.heating_rate_label = QtWidgets.QLabel(self.form_area)
        self.heating_rate_label.setObjectName("heating_rate_label")
        self.layout_6.addWidget(self.heating_rate_label)
        self.heating_rate = QtWidgets.QDoubleSpinBox(self.form_area)
        self.heating_rate.setMinimumSize(QtCore.QSize(80, 28))
        self.heating_rate.setMaximumSize(QtCore.QSize(80, 16777215))
        self.heating_rate.setMinimum(0.1)
        self.heating_rate.setMaximum(20.0)
        self.heating_rate.setObjectName("heating_rate")
        self.layout_6.addWidget(self.heating_rate)
        self.layout_4.addLayout(self.layout_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.layout_4)
        self.layout_7 = QtWidgets.QHBoxLayout()
        self.layout_7.setObjectName("layout_7")
        self.save_temp = QtWidgets.QCheckBox(self.form_area)
        self.save_temp.setObjectName("save_temp")
        self.layout_7.addWidget(self.save_temp)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_7.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.layout_7)
        self.horizontalLayout_8.addWidget(self.form_area)
        self.buttons_area = QtWidgets.QFrame(process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons_area.sizePolicy().hasHeightForWidth())
        self.buttons_area.setSizePolicy(sizePolicy)
        self.buttons_area.setMinimumSize(QtCore.QSize(0, 0))
        self.buttons_area.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.buttons_area.setFrameShape(QtWidgets.QFrame.Box)
        self.buttons_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_area.setObjectName("buttons_area")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.buttons_area)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.push_button_accept = QtWidgets.QPushButton(self.buttons_area)
        self.push_button_accept.setMinimumSize(QtCore.QSize(100, 32))
        self.push_button_accept.setShortcut("Return")
        self.push_button_accept.setObjectName("push_button_accept")
        self.verticalLayout.addWidget(self.push_button_accept)
        self.push_button_cancel = QtWidgets.QPushButton(self.buttons_area)
        self.push_button_cancel.setMinimumSize(QtCore.QSize(100, 32))
        self.push_button_cancel.setShortcut("Esc")
        self.push_button_cancel.setObjectName("push_button_cancel")
        self.verticalLayout.addWidget(self.push_button_cancel)
        self.push_button_info = QtWidgets.QPushButton(self.buttons_area)
        self.push_button_info.setMinimumSize(QtCore.QSize(100, 32))
        self.push_button_info.setObjectName("push_button_info")
        self.verticalLayout.addWidget(self.push_button_info)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_8.addWidget(self.buttons_area)

        self.retranslateUi(process)
        QtCore.QMetaObject.connectSlotsByName(process)

    def retranslateUi(self, process):
        _translate = QtCore.QCoreApplication.translate
        process.setWindowTitle(_translate("process", "TL"))
        self.final_temperature_label.setText(_translate("process", "Final Temperature (°C)"))
        self.time_at_final_temp_label.setText(_translate("process", "Time at final temperature (s)"))
        self.channels_label.setText(_translate("process", "Channels"))
        self.heating_rate_label.setText(_translate("process", "Heating Rate (°C/s)"))
        self.save_temp.setText(_translate("process", "Save Temperature"))
        self.push_button_accept.setText(_translate("process", "Accept"))
        self.push_button_cancel.setText(_translate("process", "Cancel"))
        self.push_button_info.setText(_translate("process", "Information"))

