#!/usr/bin/env python
# -*- coding: utf-8 -*- 

#~ Copyright (C) 2014 Carlos Manuel Ferras Hernandez
#~ This file is part of LF02_package.

#~ LF02_package is free software: you can redistribute it and/or modify
#~ it under the terms of the GNU General Public License as published by
#~ the Free Software Foundation, either version 3 of the License, or
#~ (at your option) any later version.

#~ LF02_package is distributed in the hope that it will be useful,
#~ but WITHOUT ANY WARRANTY; without even the implied warranty of
#~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#~ GNU General Public License for more details.

#~ You should have received a copy of the GNU General Public License
#~ along with LF02_package.  If not, see <http://www.gnu.org/licenses/>.

from PyQt4 import QtCore, QtGui
from style import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):		
		MainWindow.setObjectName(_fromUtf8("GenSec"))		
		widget=QtGui.QDesktopWidget()
		mainScreenSize = widget.availableGeometry(widget.primaryScreen())
		W= mainScreenSize.width()
		H= mainScreenSize.height()		
		MainWindow.resize(QtCore.QSize(QtCore.QRect(0,0,W,H).size()).expandedTo(MainWindow.minimumSizeHint())) 
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/gensec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		MainWindow.setWindowIcon(icon)	
		
		self.treeWidget = QtGui.QTreeWidget()		
		MainWindow.setCentralWidget(self.treeWidget)		
		self.treeWidget.setAlternatingRowColors(True)
		self.treeWidget.setIndentation(0)
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Novason"))
		font.setPointSize(12)
		font.setBold(False)
		font.setItalic(False)
		font.setUnderline(False)
		font.setWeight(53)
		font.setStrikeOut(False)
		font.setKerning(False)
		font.setStyleStrategy(QtGui.QFont.PreferDefault)
		self.treeWidget.setFont(font)
		self.treeWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
		self.treeWidget.setAcceptDrops(False)
		self.treeWidget.setFrameShape(QtGui.QFrame.StyledPanel)
		self.treeWidget.setFrameShadow(QtGui.QFrame.Sunken)
		self.treeWidget.setMidLineWidth(0)
		self.treeWidget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
		self.treeWidget.setTabKeyNavigation(True)
		self.treeWidget.setProperty("showDropIndicator", False)
		self.treeWidget.setDragDropOverwriteMode(False)
		self.treeWidget.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
		self.treeWidget.setDefaultDropAction(QtCore.Qt.MoveAction)		
		self.treeWidget.setStyleSheet(TREEW_STYLE)		
		self.treeWidget.setAlternatingRowColors(True)
		self.treeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
		self.treeWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
		self.treeWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
		self.treeWidget.setUniformRowHeights(True)
		self.treeWidget.setAnimated(False)
		self.treeWidget.setAllColumnsShowFocus(False)
		self.treeWidget.setHeaderHidden(False)
		self.treeWidget.setExpandsOnDoubleClick(True)
		self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
		self.treeWidget.headerItem().setText(0, _fromUtf8(QtGui.QApplication.translate('MainWindow',"Group")))
		self.treeWidget.headerItem().setText(1, _fromUtf8(QtGui.QApplication.translate('MainWindow',"Sample")))
		H=W%117
		num=W-H
		coe=0
		if H<55:
			num=num-55
			H+=55
			coe+=1
		cant=int(num/117)-1
		for i in range(cant):
			self.treeWidget.headerItem().setText(i+2, _fromUtf8(QtGui.QApplication.translate('MainWindow',"Command ")+str(i+1)))
		for i in range(2,cant+2):
			self.treeWidget.headerItem().setToolTip(i,QtGui.QApplication.translate('MainWindow','Add Command'))
		self.treeWidget.header().setMovable(False)		
		self.treeWidget.header().setDefaultSectionSize(117)
		self.treeWidget.header().setHighlightSections(True)
		self.treeWidget.header().setMinimumSectionSize(H)		
		self.treeWidget.setColumnWidth(0,H)
		self.treeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)

		self.menubar = QtGui.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 23))
		self.menubar.setObjectName(_fromUtf8("menubar"))
		self.menubar.setStyleSheet(MENU_STYLE)	
		self.menuArchivo = QtGui.QMenu(self.menubar)
		self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
		self.menuEditar = QtGui.QMenu(self.menubar)
		self.menuEditar.setObjectName(_fromUtf8("menuEditar"))
		self.menuOpciones = QtGui.QMenu(self.menubar)
		self.menuOpciones.setObjectName(_fromUtf8("menuOpciones"))
		self.menuOpciones_de_GenSec = QtGui.QMenu(self.menuOpciones)
		self.menuOpciones_de_GenSec.setObjectName(_fromUtf8("menuOpciones_de_GenSec"))
		self.menuOpciones_de_Secuencia = QtGui.QMenu(self.menuOpciones)
		self.menuOpciones_de_Secuencia.setObjectName(_fromUtf8("menuOpciones_de_Secuencia"))
		self.menuLanguage = QtGui.QMenu(self.menuOpciones_de_GenSec)
		self.menuLanguage.setObjectName(_fromUtf8("menuLanguage"))
		self.menuColor = QtGui.QMenu(self.menuOpciones_de_GenSec)
		self.menuColor.setObjectName(_fromUtf8("menuColor"))
		self.menuAyuda = QtGui.QMenu(self.menubar)
		self.menuAyuda.setObjectName(_fromUtf8("menuAyuda"))
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtGui.QStatusBar(MainWindow)
		self.statusbar.setObjectName(_fromUtf8("statusbar"))
		MainWindow.setStatusBar(self.statusbar)
		#Nuevo---------------------------------------------------------
		self.actionNuevo = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNuevo.setIconVisibleInMenu(True)
		self.actionNuevo.setIcon(icon)
		self.actionNuevo.setShortcut("Ctrl+N")
		self.actionNuevo.setStatusTip(QtGui.QApplication.translate("MainWindow", "Create a new file", None, QtGui.QApplication.UnicodeUTF8))
		self.actionNuevo.setObjectName(_fromUtf8("actionNuevo"))
		#Abrir-------------------------------------------------
		self.actionAbrir = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAbrir.setIconVisibleInMenu(True)
		self.actionAbrir.setIcon(icon)
		self.actionAbrir.setShortcut("Ctrl+O")
		self.actionAbrir.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open an existing file", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAbrir.setObjectName(_fromUtf8("actionAbrir"))
		#Guardar---------------------------------------------------------
		self.actionGurdar = QtGui.QAction(MainWindow)
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionGurdar.setIconVisibleInMenu(True)
		self.actionGurdar.setIcon(icon)
		self.actionGurdar.setShortcut("Ctrl+S")
		self.actionGurdar.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save the document to disk", None, QtGui.QApplication.UnicodeUTF8))
		self.actionGurdar.setObjectName(_fromUtf8("actionGurdar"))
		#GuardarComo--------------------------------------
		self.actionGurdar_como = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/save_as.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionGurdar_como.setIconVisibleInMenu(True)
		self.actionGurdar_como.setIcon(icon)
		self.actionGurdar_como.setShortcut("Ctrl+G")
		self.actionGurdar_como.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save the document under a new name", None, QtGui.QApplication.UnicodeUTF8))
		self.actionGurdar_como.setObjectName(_fromUtf8("actionGurdar_como"))
		#Vista Previa------------------------------------------
		self.actionDsdsda = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/preview.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionDsdsda.setIconVisibleInMenu(True)
		self.actionDsdsda.setIcon(icon)
		self.actionDsdsda.setShortcut("Ctrl+W")
		self.actionDsdsda.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open a PreView of the xml file", None, QtGui.QApplication.UnicodeUTF8))
		self.actionDsdsda.setObjectName(_fromUtf8("actionDsdsda"))
		#Salir--------------------------------------------
		self.actionDfgfh = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionDfgfh.setIconVisibleInMenu(True)
		self.actionDfgfh.setIcon(icon)
		self.actionDfgfh.setShortcut("Escape")
		self.actionDfgfh.setStatusTip(QtGui.QApplication.translate("MainWindow", "Close the application", None, QtGui.QApplication.UnicodeUTF8))
		self.actionDfgfh.setObjectName(_fromUtf8("actionDfgfh"))
		#Pegar--------------------------------------------------
		self.actionPegar = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/paste.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionPegar.setIconVisibleInMenu(True)
		self.actionPegar.setIcon(icon)
		self.actionPegar.setShortcut("Ctrl+V")
		self.actionPegar.setStatusTip(QtGui.QApplication.translate("MainWindow", "Paste the clipboard content into the current selection", None, QtGui.QApplication.UnicodeUTF8))
		self.actionPegar.setObjectName(_fromUtf8("actionPegar"))
		#Copiar------------------------------------------------------------
		self.actionCopiar = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/copy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionCopiar.setIconVisibleInMenu(True)
		self.actionCopiar.setIcon(icon)
		self.actionCopiar.setShortcut("Ctrl+C")
		self.actionCopiar.setStatusTip(QtGui.QApplication.translate("MainWindow", "Copy the current selection content to the clipboard", None, QtGui.QApplication.UnicodeUTF8))
		self.actionCopiar.setObjectName(_fromUtf8("actionCopiar"))
		#Borrar--------------------------------------------------------
		self.actionBorrar = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionBorrar.setIconVisibleInMenu(True)
		self.actionBorrar.setIcon(icon)
		self.actionBorrar.setShortcut("Delete")
		self.actionBorrar.setStatusTip(QtGui.QApplication.translate("MainWindow", "Delete the content of the selection rows", None, QtGui.QApplication.UnicodeUTF8))
		self.actionBorrar.setObjectName(_fromUtf8("actionBorrar"))
		#Cortar---------------------------------------------------
		self.actionCortar = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/cut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionCortar.setIconVisibleInMenu(True)
		self.actionCortar.setIcon(icon)
		self.actionCortar.setShortcut("Ctrl+X")
		self.actionCortar.setStatusTip(QtGui.QApplication.translate("MainWindow", "Cut the current selection content to the clipboard", None, QtGui.QApplication.UnicodeUTF8))
		self.actionCortar.setObjectName(_fromUtf8("actionCortar"))
		#Ayuda----------------------------------------------------
		self.actionAyuda = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAyuda.setIconVisibleInMenu(True)
		self.actionAyuda.setIcon(icon)
		self.actionAyuda.setShortcut("F1")
		self.actionAyuda.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open the help of the application", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAyuda.setObjectName(_fromUtf8("actionAyuda"))
		#AcercaDe----------------------------------------------------
		self.actionAcerda_de = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAcerda_de.setIconVisibleInMenu(True)
		self.actionAcerda_de.setIcon(icon)
		self.actionAcerda_de.setShortcut("Ctrl+I")
		self.actionAcerda_de.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show information about the application", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAcerda_de.setObjectName(_fromUtf8("actionAcerda_de"))
		#Imprimir-------------------------------------------------
		self.actionImprimir = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionImprimir.setIconVisibleInMenu(True)
		self.actionImprimir.setIcon(icon)
		self.actionImprimir.setShortcut("Ctrl+P")
		self.actionImprimir.setStatusTip(QtGui.QApplication.translate("MainWindow", "Print the current table", None, QtGui.QApplication.UnicodeUTF8))
		self.actionImprimir.setObjectName(_fromUtf8("actionImprimir"))
		#Limpiar---------------------------------------------------
		self.actionLimpiar = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionLimpiar.setIconVisibleInMenu(True)
		self.actionLimpiar.setIcon(icon)
		self.actionLimpiar.setShortcut("Ctrl+Q")
		self.actionLimpiar.setStatusTip(QtGui.QApplication.translate("MainWindow", "Delete all the content of the table", None, QtGui.QApplication.UnicodeUTF8))
		self.actionLimpiar.setObjectName(_fromUtf8("actionLimpiar"))
		#Fuente---------------------------------------------------------
		self.actionFuente = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/font.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionFuente.setIconVisibleInMenu(True)
		self.actionFuente.setIcon(icon)
		self.actionFuente.setShortcut("Ctrl+F")
		self.actionFuente.setStatusTip(QtGui.QApplication.translate("MainWindow", "Change the font type and size", None, QtGui.QApplication.UnicodeUTF8))
		self.actionFuente.setObjectName(_fromUtf8("actionFuente"))
		#Directorio por defecto---------------------------------------------------------
		self.actionDir_defecto = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/default_dir.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionDir_defecto.setIconVisibleInMenu(True)
		self.actionDir_defecto.setIcon(icon)
		self.actionDir_defecto.setShortcut("Ctrl+D")
		self.actionDir_defecto.setStatusTip(QtGui.QApplication.translate("MainWindow", "Change the default file location", None, QtGui.QApplication.UnicodeUTF8))
		self.actionDir_defecto.setObjectName(_fromUtf8("actionDir_defecto"))		
		#Window Opacity---------------------------------------------------------
		self.actionOpacity = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/opacity.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionOpacity.setIconVisibleInMenu(True)
		self.actionOpacity.setIcon(icon)
		self.actionOpacity.setShortcut("Ctrl+Y")
		self.actionOpacity.setStatusTip(QtGui.QApplication.translate("MainWindow", "Change the opacity of the windows", None, QtGui.QApplication.UnicodeUTF8))
		self.actionOpacity.setObjectName(_fromUtf8("actionOpacity"))
		#Color1---------------------------------------------------------
		self.actionColor1= QtGui.QAction(MainWindow)
		self.actionColor1.setObjectName(_fromUtf8("actionColor1"))
		#Color2---------------------------------------------------------
		self.actionColor2= QtGui.QAction(MainWindow)
		self.actionColor2.setObjectName(_fromUtf8("actionColor2"))
		#Color3---------------------------------------------------------
		self.actionColor3= QtGui.QAction(MainWindow)
		self.actionColor3.setObjectName(_fromUtf8("actionColor3"))
		#Reset----------------------------------
		self.actionReset = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/reset.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionReset.setIconVisibleInMenu(True)
		self.actionReset.setIcon(icon)
		self.actionReset.setShortcut("Ctrl+K")
		self.actionReset.setStatusTip(QtGui.QApplication.translate("MainWindow", "Set all states to 'pend', clean all 'data' tags of all process and restores name, datecreation and reader ID of the sequence.", None, QtGui.QApplication.UnicodeUTF8))
		self.actionReset.setObjectName(_fromUtf8("actionReset"))
		#Ejecutar Comando***
		self.actionEjecutar_Comando = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/run.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionEjecutar_Comando.setIconVisibleInMenu(True)
		self.actionEjecutar_Comando.setIcon(icon)
		self.actionEjecutar_Comando.setShortcut("Ctrl+R")
		self.actionEjecutar_Comando.setObjectName(_fromUtf8("actionEjecutar_Comando"))
		#Ejecutar Analyzer-------------------------------------------------------------
		self.actionEjecutar_Analyzer = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/genvis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionEjecutar_Analyzer.setIconVisibleInMenu(True)
		self.actionEjecutar_Analyzer.setIcon(icon)
		self.actionEjecutar_Analyzer.setShortcut("Ctrl+R")
		self.actionEjecutar_Analyzer.setObjectName(_fromUtf8("actionEjecutar_Analyzer"))
		#Adicionar Fila-----------------------------------------------------------
		self.actionAdicionar_Fila = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/add_row.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAdicionar_Fila.setIconVisibleInMenu(True)
		self.actionAdicionar_Fila.setIcon(icon)
		self.actionAdicionar_Fila.setShortcut("F9")
		self.actionAdicionar_Fila.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add one row at end of the table", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAdicionar_Fila.setObjectName(_fromUtf8("actionAdicionar_Fila"))
		#Adicionar Columna----------------------------------------------------
		self.actionAdicionar_Columna = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/add_column.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAdicionar_Columna.setIconVisibleInMenu(True)
		self.actionAdicionar_Columna.setIcon(icon)
		self.actionAdicionar_Columna.setShortcut("F10")
		self.actionAdicionar_Columna.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add one column at end of the table", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAdicionar_Columna.setObjectName(_fromUtf8("actionAdicionar_Columna"))
		#Seleccionar Fila-----------------------------------------------------------------
		self.actionSeleccionar_Fila = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/select_row.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionSeleccionar_Fila.setIconVisibleInMenu(True)
		self.actionSeleccionar_Fila.setIcon(icon)
		self.actionSeleccionar_Fila.setShortcut("Alt+S")
		self.actionSeleccionar_Fila.setStatusTip(QtGui.QApplication.translate("MainWindow", "Select one row of the table", None, QtGui.QApplication.UnicodeUTF8))
		self.actionSeleccionar_Fila.setObjectName(_fromUtf8("actionSeleccionar_Fila"))
		#Nombre----------------------------------------------------------------------------
		self.actionNombre = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/name.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNombre.setIconVisibleInMenu(True)
		self.actionNombre.setIcon(icon)
		self.actionNombre.setStatusTip(QtGui.QApplication.translate("MainWindow", "Change the sequence's name", None, QtGui.QApplication.UnicodeUTF8))
		self.actionNombre.setObjectName(_fromUtf8("actionNombre"))
		#Propietario---------------------------------------------------------------
		self.actionPropietario = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/owner.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionPropietario.setIconVisibleInMenu(True)
		self.actionPropietario.setIcon(icon)
		self.actionPropietario.setStatusTip(QtGui.QApplication.translate("MainWindow", "Change the name of the sequence's owner", None, QtGui.QApplication.UnicodeUTF8))
		self.actionPropietario.setObjectName(_fromUtf8("actionPropietario"))
		#Nitrogeno------------------------------------------------------
		self.actionUso_de_Nitr_geno = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/nitrogen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionUso_de_Nitr_geno.setIconVisibleInMenu(True)
		self.actionUso_de_Nitr_geno.setIcon(icon)
		self.actionUso_de_Nitr_geno.setStatusTip(QtGui.QApplication.translate("MainWindow", "Change the use of nitrogen in the sequence", None, QtGui.QApplication.UnicodeUTF8))
		self.actionUso_de_Nitr_geno.setObjectName(_fromUtf8("actionUso_de_Nitr_geno"))
		#Tasa de dosis----------------------------------
		self.actionT_sa_de_Dosis = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/dose_rate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionT_sa_de_Dosis.setIconVisibleInMenu(True)
		self.actionT_sa_de_Dosis.setIcon(icon)
		self.actionT_sa_de_Dosis.setStatusTip(QtGui.QApplication.translate("MainWindow", "Change the dose rate of the sequence", None, QtGui.QApplication.UnicodeUTF8))
		self.actionT_sa_de_Dosis.setObjectName(_fromUtf8("actionT_sa_de_Dosis"))
		#Tasa de dosis externa-------------------------------------------
		self.actionTasa_de_Dosis_Externa = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/ext_dose_rate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionTasa_de_Dosis_Externa.setIconVisibleInMenu(True)
		self.actionTasa_de_Dosis_Externa.setIcon(icon)
		self.actionTasa_de_Dosis_Externa.setStatusTip(QtGui.QApplication.translate("MainWindow", "Change the external dose rate of the sequence", None, QtGui.QApplication.UnicodeUTF8))
		self.actionTasa_de_Dosis_Externa.setObjectName(_fromUtf8("actionTasa_de_Dosis_Externa"))
		#Protocolo-----------------------------------------------------------
		self.actionProtocolo = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/protocol.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionProtocolo.setIconVisibleInMenu(True)
		self.actionProtocolo.setIcon(icon)
		self.actionProtocolo.setStatusTip(QtGui.QApplication.translate("MainWindow", "Change the protocol of the sequence", None, QtGui.QApplication.UnicodeUTF8))
		self.actionProtocolo.setObjectName(_fromUtf8("actionProtocolo"))
		#Reader_id-----------------------------------------------------------
		self.actionReaderId = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/reader_id.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionReaderId.setIconVisibleInMenu(True)
		self.actionReaderId.setIcon(icon)
		self.actionReaderId.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show the sequence's  reader id", None, QtGui.QApplication.UnicodeUTF8))
		self.actionReaderId.setObjectName(_fromUtf8("actionReaderId"))
		#Merge----------------------------------------------------------------
		self.toolButton_6 = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/merge.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.toolButton_6.setIcon(icon)
		self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
		self.toolButton_6.setToolTip(QtGui.QApplication.translate("MainWindow",'Merge', None, QtGui.QApplication.UnicodeUTF8))
		self.toolButton_6.setEnabled(False)
		self.toolButton_6.setStatusTip(QtGui.QApplication.translate("MainWindow", "Merge several commands in the same proces_order", None, QtGui.QApplication.UnicodeUTF8))
		#Destroy Merge----------------------------------------------------------------
		self.toolButton_7 = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/icons/cancel_merge.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.toolButton_7.setIcon(icon)
		self.toolButton_7.setObjectName(_fromUtf8("toolButton_7"))
		self.toolButton_7.setToolTip(QtGui.QApplication.translate("MainWindow",'Split', None, QtGui.QApplication.UnicodeUTF8))
		self.toolButton_7.setEnabled(False)
		self.toolButton_7.setStatusTip(QtGui.QApplication.translate("MainWindow", "Split the selected merges ", None, QtGui.QApplication.UnicodeUTF8))
		
		self.menuArchivo.addAction(self.actionNuevo)
		self.menuArchivo.addAction(self.actionAbrir)
		self.menuArchivo.addAction(self.actionGurdar)
		self.menuArchivo.addAction(self.actionGurdar_como)
		self.menuArchivo.addSeparator()
		self.menuArchivo.addAction(self.actionDsdsda)
		self.menuArchivo.addAction(self.actionLimpiar)
		self.menuArchivo.addAction(self.actionImprimir)
		self.menuArchivo.addSeparator()
		self.menuArchivo.addAction(self.actionDfgfh)
		self.menuEditar.addSeparator()
		self.menuEditar.addSeparator()
		self.menuEditar.addAction(self.actionPegar)
		self.menuEditar.addAction(self.actionCopiar)
		self.menuEditar.addAction(self.actionCortar)
		self.menuEditar.addSeparator()
		self.menuEditar.addAction(self.actionAdicionar_Fila)
		self.menuEditar.addAction(self.actionAdicionar_Columna)
		self.menuEditar.addAction(self.actionSeleccionar_Fila)
		self.menuEditar.addSeparator()
		self.menuEditar.addAction(self.actionBorrar)
		self.menuOpciones_de_GenSec.addAction(self.menuLanguage.menuAction())	
		self.menuOpciones_de_GenSec.addAction(self.actionFuente)
		self.menuOpciones_de_GenSec.addAction(self.actionDir_defecto)
		self.menuOpciones_de_GenSec.addAction(self.actionOpacity)		
		self.menuOpciones_de_GenSec.addAction(self.menuColor.menuAction())		
		self.menuColor.addAction(self.actionColor1)
		self.menuColor.addAction(self.actionColor2)
		self.menuColor.addAction(self.actionColor3)		
		self.menuOpciones_de_Secuencia.addAction(self.actionNombre)
		self.menuOpciones_de_Secuencia.addAction(self.actionPropietario)
		self.menuOpciones_de_Secuencia.addAction(self.actionUso_de_Nitr_geno)
		self.menuOpciones_de_Secuencia.addAction(self.actionT_sa_de_Dosis)
		self.menuOpciones_de_Secuencia.addAction(self.actionTasa_de_Dosis_Externa)
		self.menuOpciones_de_Secuencia.addAction(self.actionProtocolo)
		self.menuOpciones_de_Secuencia.addAction(self.actionReaderId)
		self.menuOpciones.addAction(self.menuOpciones_de_Secuencia.menuAction())
		self.menuOpciones.addAction(self.menuOpciones_de_GenSec.menuAction())		
		self.menuOpciones.addAction(self.actionReset)
		self.menuOpciones.addAction(self.actionEjecutar_Comando)
		self.menuOpciones.addAction(self.actionEjecutar_Analyzer)		
		self.menuAyuda.addSeparator()
		self.menuAyuda.addAction(self.actionAyuda)
		self.menuAyuda.addSeparator()
		self.menuAyuda.addAction(self.actionAcerda_de)
		self.menubar.addAction(self.menuArchivo.menuAction())
		self.menubar.addAction(self.menuEditar.menuAction())
		self.menubar.addAction(self.menuOpciones.menuAction())
		self.menubar.addAction(self.menuAyuda.menuAction())

		self.ToolBar= MainWindow.addToolBar(QtGui.QApplication.translate("MainWindow","Tool bar"))
		self.ToolBar.setStyleSheet(TOOLBUTTON_STYLE)
		self.ToolBar.addAction(self.actionNuevo)
		self.ToolBar.addAction(self.actionAbrir)
		self.ToolBar.addAction(self.actionGurdar)
		self.ToolBar.addAction(self.actionDsdsda) #VP		
		self.ToolBar.addAction(self.actionImprimir )
		self.ToolBar.addSeparator()
		self.ToolBar.addAction(self.toolButton_6)
		self.ToolBar.addAction(self.toolButton_7)
		self.ToolBar.addAction(self.actionReset)
		self.ToolBar.addSeparator()
		self.ToolBar.addAction(self.actionEjecutar_Comando)
		self.ToolBar.addAction(self.actionEjecutar_Analyzer)	
		

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
		MainWindow.setWindowTitle("GenSec")
		__sortingEnabled = self.treeWidget.isSortingEnabled()
		self.treeWidget.setSortingEnabled(False)
		self.treeWidget.setSortingEnabled(__sortingEnabled)
		self.menuArchivo.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
		self.menuEditar.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
		self.menuOpciones.setTitle(QtGui.QApplication.translate("MainWindow", "&Options", None, QtGui.QApplication.UnicodeUTF8))
		self.menuOpciones_de_GenSec.setTitle(QtGui.QApplication.translate("MainWindow", "&GenSec Options", None, QtGui.QApplication.UnicodeUTF8))
		self.menuColor.setTitle(QtGui.QApplication.translate("MainWindow", "&Merge Colors", None, QtGui.QApplication.UnicodeUTF8))
		self.menuLanguage.setTitle(QtGui.QApplication.translate("MainWindow", "&Select Language", None, QtGui.QApplication.UnicodeUTF8))
		self.menuOpciones_de_Secuencia.setTitle(QtGui.QApplication.translate("MainWindow", "&Sequence Options", None, QtGui.QApplication.UnicodeUTF8))
		self.menuAyuda.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
		self.actionNuevo.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAbrir.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
		self.actionGurdar.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
		self.actionGurdar_como.setText(QtGui.QApplication.translate("MainWindow", "Save &as..", None, QtGui.QApplication.UnicodeUTF8))
		self.actionDsdsda.setText(QtGui.QApplication.translate("MainWindow", "&Preview", None, QtGui.QApplication.UnicodeUTF8))
		self.actionDfgfh.setText(QtGui.QApplication.translate("MainWindow", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
		self.actionPegar.setText(QtGui.QApplication.translate("MainWindow", "&Paste", None, QtGui.QApplication.UnicodeUTF8))
		self.actionCopiar.setText(QtGui.QApplication.translate("MainWindow", "&Copy", None, QtGui.QApplication.UnicodeUTF8))
		self.actionBorrar.setText(QtGui.QApplication.translate("MainWindow", "Cl&ear Seleccion", None, QtGui.QApplication.UnicodeUTF8))
		self.actionCortar.setText(QtGui.QApplication.translate("MainWindow", "C&ut", None, QtGui.QApplication.UnicodeUTF8))		
		self.actionColor1.setText(QtGui.QApplication.translate("MainWindow", "Color &1", None, QtGui.QApplication.UnicodeUTF8))
		self.actionColor2.setText(QtGui.QApplication.translate("MainWindow", "Color &2", None, QtGui.QApplication.UnicodeUTF8))
		self.actionColor3.setText(QtGui.QApplication.translate("MainWindow", "Color &3", None, QtGui.QApplication.UnicodeUTF8))		
		self.actionAyuda.setText(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAcerda_de.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
		self.actionImprimir.setText(QtGui.QApplication.translate("MainWindow", "Prin&t", None, QtGui.QApplication.UnicodeUTF8))
		self.actionLimpiar.setText(QtGui.QApplication.translate("MainWindow", "&Clear All", None, QtGui.QApplication.UnicodeUTF8))
		self.actionFuente.setText(QtGui.QApplication.translate("MainWindow", "&Font", None, QtGui.QApplication.UnicodeUTF8))
		self.actionDir_defecto.setText(QtGui.QApplication.translate("MainWindow", "&Default Location", None, QtGui.QApplication.UnicodeUTF8))
		self.actionOpacity.setText(QtGui.QApplication.translate("MainWindow", "Window &Opacity", None, QtGui.QApplication.UnicodeUTF8))
		self.actionReset.setText(QtGui.QApplication.translate("MainWindow", "Rese&t", None, QtGui.QApplication.UnicodeUTF8))
		self.actionEjecutar_Comando.setText(QtGui.QApplication.translate("MainWindow", "&Run Command", None, QtGui.QApplication.UnicodeUTF8))
		self.actionEjecutar_Analyzer.setText(QtGui.QApplication.translate("MainWindow", "&Run Sequence analyzer", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAdicionar_Fila.setText(QtGui.QApplication.translate("MainWindow", "Add &Row", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAdicionar_Columna.setText(QtGui.QApplication.translate("MainWindow", "Add Colu&mn", None, QtGui.QApplication.UnicodeUTF8))
		self.actionSeleccionar_Fila.setText(QtGui.QApplication.translate("MainWindow", "&Select Row", None, QtGui.QApplication.UnicodeUTF8))
		self.actionNombre.setText(QtGui.QApplication.translate("MainWindow", "&Name", None, QtGui.QApplication.UnicodeUTF8))
		self.actionPropietario.setText(QtGui.QApplication.translate("MainWindow", "&Owner", None, QtGui.QApplication.UnicodeUTF8))
		self.actionUso_de_Nitr_geno.setText(QtGui.QApplication.translate("MainWindow", "Nitrogen &Use", None, QtGui.QApplication.UnicodeUTF8))
		self.actionT_sa_de_Dosis.setText(QtGui.QApplication.translate("MainWindow", "&Dose Rate", None, QtGui.QApplication.UnicodeUTF8))
		self.actionTasa_de_Dosis_Externa.setText(QtGui.QApplication.translate("MainWindow", "&External Dose Rate", None, QtGui.QApplication.UnicodeUTF8))
		self.actionProtocolo.setText(QtGui.QApplication.translate("MainWindow", "&Protocol", None, QtGui.QApplication.UnicodeUTF8))
		self.actionReaderId.setText(QtGui.QApplication.translate("MainWindow", "&Reader ID", None, QtGui.QApplication.UnicodeUTF8))
		